// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def channel = userVars?.get('channel')?.toString()
def hasChannel = (channel != null && !channel.isEmpty())

// ─── Widget: pivot_dd06-pivot-weekday-hour (type=pivot, dataSource=sql) ───
if (!componentId || componentId == 'pivot_dd06-pivot-weekday-hour') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT dayname(o.order_ts) AS weekday,\n'
    sql << '       lpad(hour(o.order_ts)::VARCHAR, 2, \'0\') AS hour_of_day,\n'
    sql << '       count(*) AS orders\n'
    sql << 'FROM dash_demo.orders o\n'
    if (hasChannel) {
        sql << 'WHERE o.channel = ?\n'
        params << asDeclaredType('channel', 'String', channel)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1, 2\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('pivot_dd06-pivot-weekday-hour', data)
}

// ─── Widget: chart_dd06-chart-orders-by-month-of-year (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd06-chart-orders-by-month-of-year') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT *\n'
    sql << 'FROM (\n'
    sql << '  SELECT CAST(month("order_ts") AS INTEGER) AS "order_ts", COUNT("order_id") AS "order_id_count"\n'
    sql << '  FROM "dash_demo"."orders"\n'
    if (hasChannel) {
        sql << '  WHERE "channel" = ?\n'
        params << asDeclaredType('channel', 'String', channel)
    } else {
        sql << '  WHERE 1=1\n'   // no value: this filter is off
    }
    sql << '  GROUP BY CAST(month("order_ts") AS INTEGER)\n'
    sql << ') grouped_rows\n'
    sql << 'ORDER BY CASE WHEN "order_ts" IS NULL THEN 1 ELSE 0 END, "order_ts" ASC\n'
    sql << 'LIMIT 12\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd06-chart-orders-by-month-of-year', data)
}

// ─── Widget: chart_dd06-chart-average-by-day-of-month (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd06-chart-average-by-day-of-month') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH per_day AS (\n'
    sql << '  SELECT date_trunc(\'month\', o.order_ts) AS month,\n'
    sql << '         day(o.order_ts) AS day_of_month,\n'
    sql << '         count(*) AS n\n'
    sql << '  FROM dash_demo.orders o\n'
    if (hasChannel) {
        sql << '  WHERE o.channel = ?\n'
        params << asDeclaredType('channel', 'String', channel)
    } else {
        sql << '  WHERE 1=1\n'   // no value: this filter is off
    }
    sql << '  GROUP BY 1, 2\n'
    sql << '), month_average AS (\n'
    sql << '  SELECT month, avg(n) AS avg_n FROM per_day GROUP BY 1\n'
    sql << ')\n'
    sql << 'SELECT p.day_of_month AS day_of_month,\n'
    sql << '       round(avg(p.n), 2) AS avg_orders,\n'
    sql << '       round(100.0 * avg(p.n / m.avg_n), 4) AS pct_of_daily_average\n'
    sql << 'FROM per_day p\n'
    sql << 'JOIN month_average m USING (month)\n'
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd06-chart-average-by-day-of-month', data)
}

// ─── Widget: chart_dd06-chart-daily-orders-black-friday (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd06-chart-daily-orders-black-friday') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.order_ts::DATE AS day,\n'
    sql << '       count(*) AS orders\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.order_ts >= date_trunc(\'year\', (SELECT a.as_of FROM dash_demo.as_of a)) - INTERVAL 2 MONTH\n'
    sql << '  AND o.order_ts < date_trunc(\'year\', (SELECT a.as_of FROM dash_demo.as_of a)) - INTERVAL 16 DAY\n'
    if (hasChannel) {
        sql << '  AND o.channel = ?\n'
        params << asDeclaredType('channel', 'String', channel)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd06-chart-daily-orders-black-friday', data)
}

