// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.DateParameters
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// The day after a date: where a range of whole days ends, so that its last day counts
// in full. An empty value stays empty.
def dayAfter = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return DateParameters.nextDay(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def team = userVars?.get('team')?.toString()
def hasTeam = (team != null && !team.isEmpty())
def dateFrom = userVars?.get('dateFrom')?.toString()
def hasDateFrom = (dateFrom != null && !dateFrom.isEmpty())
def dateTo = userVars?.get('dateTo')?.toString()
def hasDateTo = (dateTo != null && !dateTo.isEmpty())
def dateTo__next_day = dayAfter('dateTo', 'Date', dateTo)
def hasDateTo__next_day = (dateTo__next_day != null && !dateTo__next_day.isEmpty())

// ─── Widget: trend_month_csat (type=trend, dataSource=sql) ───
if (!componentId || componentId == 'trend_month_csat') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT date_trunc(\'month\', t.opened_ts)::DATE AS month,\n'
    sql << '       round(avg(t.csat_score), 2) AS avg_csat\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND t.opened_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND t.opened_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY month\n'
    sql << 'ORDER BY month\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('trend_month_csat', data)
}

// ─── Widget: progress_dd22-progress-team-sla (type=progress, dataSource=sql) ───
if (!componentId || componentId == 'progress_dd22-progress-team-sla') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(count(CASE WHEN NOT t.sla_breached THEN 1 END) / count(*)::DOUBLE\n'
    sql << '             * 100.0 / (SELECT k.target FROM dash_demo.kpi_targets k WHERE k.area = \'Support\' AND k.kpi = \'sla_met\'), 4) AS pct_of_target\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND t.opened_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND t.opened_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('progress_dd22-progress-team-sla', data)
}

// ─── Widget: number_reopened_rate_reopened (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_reopened_rate_reopened') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(count(CASE WHEN t.reopened THEN 1 END) / count(*)::DOUBLE, 4) AS reopened_rate\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND t.opened_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND t.opened_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_reopened_rate_reopened', data)
}

// ─── Widget: chart_dd22-chart-boxplot-resolution-hours-by-channel (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd22-chart-boxplot-resolution-hours-by-channel') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT t.channel AS channel,\n'
    sql << '       round(date_diff(\'minute\', t.opened_ts, t.resolved_ts) / 60.0, 2) AS resolution_hours\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND t.opened_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND t.opened_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND t.resolved_ts IS NOT NULL\n'
    sql << 'ORDER BY t.channel, resolution_hours\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd22-chart-boxplot-resolution-hours-by-channel', data)
}

// ─── Widget: chart_dd22-chart-csat-by-channel (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd22-chart-csat-by-channel') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  dash_demo.support_tickets.channel AS "Channel",\n'
    sql << '  CAST(AVG(CAST(dash_demo.support_tickets.csat_score AS DECIMAL(31,4))) AS DECIMAL(31,4)) AS "AvgCsat"\n'
    sql << 'FROM dash_demo.support_tickets\n'
    sql << 'LEFT JOIN dash_demo.support_agents ON dash_demo.support_tickets.agent_id = dash_demo.support_agents.agent_id\n'
    if (hasDateTo__next_day) {
        sql << 'WHERE dash_demo.support_tickets.opened_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasTeam) {
        sql << '  AND dash_demo.support_agents.team = ?\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateFrom) {
        sql << '  AND dash_demo.support_tickets.opened_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY\n'
    sql << '  dash_demo.support_tickets.channel\n'
    sql << 'ORDER BY\n'
    sql << '  "AvgCsat" DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd22-chart-csat-by-channel', data)
}

// ─── Widget: tabulator_dd22-table-agent-leaderboard (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd22-table-agent-leaderboard') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT sa.name AS agent,\n'
    sql << '       sa.team AS team,\n'
    sql << '       count(*) AS tickets,\n'
    sql << '       round(avg(date_diff(\'minute\', t.opened_ts, t.resolved_ts) / 60.0), 2) AS avg_resolution_hours,\n'
    sql << '       round(avg(t.csat_score), 2) AS avg_csat,\n'
    sql << '       round(100.0 * count(CASE WHEN NOT t.sla_breached THEN 1 END) / count(*), 2) AS sla_met_pct\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'JOIN dash_demo.support_agents sa ON sa.agent_id = t.agent_id\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND t.opened_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND t.opened_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY sa.name, sa.team\n'
    sql << 'ORDER BY tickets DESC, agent\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd22-table-agent-leaderboard', data)
}

