// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.DateParameters
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// The day after a date: where a range of whole days ends, so that its last day counts
// in full. An empty value stays empty.
def dayAfter = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return DateParameters.nextDay(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def repEmployeeId = userVars?.get('repEmployeeId')?.toString()
def hasRepEmployeeId = (repEmployeeId != null && !repEmployeeId.isEmpty())
def closeFrom = userVars?.get('closeFrom')?.toString()
def hasCloseFrom = (closeFrom != null && !closeFrom.isEmpty())
def closeTo = userVars?.get('closeTo')?.toString()
def hasCloseTo = (closeTo != null && !closeTo.isEmpty())
def closeTo__next_day = dayAfter('closeTo', 'Date', closeTo)
def hasCloseTo__next_day = (closeTo__next_day != null && !closeTo__next_day.isEmpty())

// ─── Widget: number_open_pipeline_pipeline (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_open_pipeline_pipeline') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(c.amount), 2) AS open_pipeline\n'
    sql << 'FROM dash_demo.crm_opportunities c\n'
    sql << 'WHERE c.stage NOT IN (\'won\', \'lost\')\n'
    if (hasCloseFrom) {
        sql << '  AND c.expected_close_date >= ?\n'
        params << asDeclaredType('closeFrom', 'Date', closeFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCloseTo) {
        sql << '  AND c.expected_close_date <= ?\n'
        params << asDeclaredType('closeTo', 'Date', closeTo)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasRepEmployeeId) {
        sql << '  AND c.owner_employee_id = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_open_pipeline_pipeline', data)
}

// ─── Widget: number_weighted_pipeline_pipeline (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_weighted_pipeline_pipeline') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(c.amount * c.probability_pct / 100.0), 2) AS weighted_pipeline\n'
    sql << 'FROM dash_demo.crm_opportunities c\n'
    sql << 'WHERE c.stage NOT IN (\'won\', \'lost\')\n'
    if (hasCloseFrom) {
        sql << '  AND c.expected_close_date >= ?\n'
        params << asDeclaredType('closeFrom', 'Date', closeFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCloseTo) {
        sql << '  AND c.expected_close_date <= ?\n'
        params << asDeclaredType('closeTo', 'Date', closeTo)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasRepEmployeeId) {
        sql << '  AND c.owner_employee_id = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_weighted_pipeline_pipeline', data)
}

// ─── Widget: gauge_quota_attainment_attainment (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_quota_attainment_attainment') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(\n'
    sql << '         (SELECT sum(c.amount) FROM dash_demo.crm_opportunities c\n'
    sql << '          WHERE c.stage = \'won\'\n'
    sql << '            AND c.closed_date >= date_trunc(\'quarter\', (SELECT a.as_of FROM dash_demo.as_of a))\n'
    sql << '            AND c.closed_date <= (SELECT a.as_of FROM dash_demo.as_of a)\n'
    if (hasRepEmployeeId) {
        sql << '            AND c.owner_employee_id = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '            AND 1=1\n'   // no value: this filter is off
    }
    sql << '         )\n'
    sql << '       / (SELECT sum(q.quota) FROM dash_demo.rep_quotas q\n'
    sql << '          WHERE q.quarter_start = date_trunc(\'quarter\', (SELECT a.as_of FROM dash_demo.as_of a))\n'
    if (hasRepEmployeeId) {
        sql << '            AND q.employee_id = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '            AND 1=1\n'   // no value: this filter is off
    }
    sql << '         ), 4) AS quota_attainment\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_quota_attainment_attainment', data)
}

// ─── Widget: number_next_quarter_cover_cover (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_next_quarter_cover_cover') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(\n'
    sql << '         (SELECT sum(c.amount) FROM dash_demo.crm_opportunities c\n'
    sql << '          WHERE c.stage NOT IN (\'won\', \'lost\')\n'
    sql << '            AND c.expected_close_date >= date_trunc(\'quarter\', (SELECT a.as_of FROM dash_demo.as_of a)) + INTERVAL 3 MONTH\n'
    sql << '            AND c.expected_close_date < date_trunc(\'quarter\', (SELECT a.as_of FROM dash_demo.as_of a)) + INTERVAL 6 MONTH\n'
    if (hasRepEmployeeId) {
        sql << '            AND c.owner_employee_id = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '            AND 1=1\n'   // no value: this filter is off
    }
    sql << '         )\n'
    sql << '       / (SELECT sum(q.quota) FROM dash_demo.rep_quotas q\n'
    sql << '          WHERE q.quarter_start = date_trunc(\'quarter\', (SELECT a.as_of FROM dash_demo.as_of a)) + INTERVAL 3 MONTH\n'
    if (hasRepEmployeeId) {
        sql << '            AND q.employee_id = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '            AND 1=1\n'   // no value: this filter is off
    }
    sql << '         ), 2) AS next_quarter_cover\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_next_quarter_cover_cover', data)
}

// ─── Widget: chart_dd07-chart-deals-by-stage (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd07-chart-deals-by-stage') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT c.stage AS stage,\n'
    sql << '       count(*) AS deals,\n'
    sql << '       round(sum(c.amount), 2) AS pipeline\n'
    sql << 'FROM dash_demo.crm_opportunities c\n'
    sql << 'WHERE c.stage NOT IN (\'won\', \'lost\')\n'
    if (hasRepEmployeeId) {
        sql << '  AND c.owner_employee_id = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY deals DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd07-chart-deals-by-stage', data)
}

// ─── Widget: chart_dd07-chart-win-rate-by-lead-source (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd07-chart-win-rate-by-lead-source') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT c.lead_source AS lead_source,\n'
    sql << '       round(100.0 * count(CASE WHEN c.stage = \'won\' THEN 1 END) / count(*), 2) AS win_rate_pct,\n'
    sql << '       count(*) AS closed_deals\n'
    sql << 'FROM dash_demo.crm_opportunities c\n'
    sql << 'WHERE c.stage IN (\'won\', \'lost\')\n'
    if (hasRepEmployeeId) {
        sql << '  AND c.owner_employee_id = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY win_rate_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd07-chart-win-rate-by-lead-source', data)
}

// ─── Widget: tabulator_crm_opportunities_deals (type=tabulator, dataSource=visual) ───
if (!componentId || componentId == 'tabulator_crm_opportunities_deals') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT *\n'
    sql << 'FROM "dash_demo"."crm_opportunities"\n'
    sql << 'WHERE "stage" NOT IN (\'won\', \'lost\')\n'
    if (hasCloseFrom && hasCloseTo__next_day) {
        sql << '  AND "expected_close_date" >= ? AND "expected_close_date" < ?\n'
        params << asDeclaredType('closeFrom', 'Date', closeFrom)
        params << asDeclaredType('closeTo__next_day', 'Date', closeTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasRepEmployeeId) {
        sql << '  AND "owner_employee_id" = ?\n'
        params << asDeclaredType('repEmployeeId', 'String', repEmployeeId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'ORDER BY CASE WHEN "expected_close_date" IS NULL THEN 1 ELSE 0 END, "expected_close_date" asc\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_crm_opportunities_deals', data)
}

