// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.DateParameters
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// The day after a date: where a range of whole days ends, so that its last day counts
// in full. An empty value stays empty.
def dayAfter = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return DateParameters.nextDay(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def dateFrom = userVars?.get('dateFrom')?.toString()
def hasDateFrom = (dateFrom != null && !dateFrom.isEmpty())
def dateTo = userVars?.get('dateTo')?.toString()
def hasDateTo = (dateTo != null && !dateTo.isEmpty())
def carrier = userVars?.get('carrier')?.toString()
def hasCarrier = (carrier != null && !carrier.isEmpty())
def dateTo__next_day = dayAfter('dateTo', 'Date', dateTo)
def hasDateTo__next_day = (dateTo__next_day != null && !dateTo__next_day.isEmpty())

// ─── Widget: gauge_on_time_rate_delivery (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_on_time_rate_delivery') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(count(CASE WHEN o.delivered_ts::DATE <= o.promised_date THEN 1 END)\n'
    sql << '             / count(*)::DOUBLE, 4) AS on_time_rate\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasDateFrom) {
        sql << '  AND o.delivered_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.delivered_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCarrier && listHasValues(carrier)) {
        addInList(sql, params, carrier, 'AND o.carrier IN') { asDeclaredType('carrier', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_on_time_rate_delivery', data)
}

// ─── Widget: number_average_days_to_deliver_deliver (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_average_days_to_deliver_deliver') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(avg(date_diff(\'day\', o.order_ts::DATE, o.delivered_ts::DATE)), 2) AS average_days_to_deliver\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasDateFrom) {
        sql << '  AND o.delivered_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.delivered_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCarrier && listHasValues(carrier)) {
        addInList(sql, params, carrier, 'AND o.carrier IN') { asDeclaredType('carrier', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_average_days_to_deliver_deliver', data)
}

// ─── Widget: number_late_orders_orders (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_late_orders_orders') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) AS late_orders\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasDateFrom) {
        sql << '  AND o.delivered_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.delivered_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCarrier && listHasValues(carrier)) {
        addInList(sql, params, carrier, 'AND o.carrier IN') { asDeclaredType('carrier', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  AND o.delivered_ts::DATE > o.promised_date\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_late_orders_orders', data)
}

// ─── Widget: trend_week_week (type=trend, dataSource=sql) ───
if (!componentId || componentId == 'trend_week_week') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT date_trunc(\'week\', o.delivered_ts)::DATE AS week,\n'
    sql << '       round(count(CASE WHEN o.delivered_ts::DATE <= o.promised_date THEN 1 END)\n'
    sql << '             / count(*)::DOUBLE, 4) AS on_time_rate\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasDateFrom) {
        sql << '  AND o.delivered_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.delivered_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCarrier && listHasValues(carrier)) {
        addInList(sql, params, carrier, 'AND o.carrier IN') { asDeclaredType('carrier', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY week\n'
    sql << 'ORDER BY week\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('trend_week_week', data)
}

// ─── Widget: chart_dd20-chart-late-by-carrier (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd20-chart-late-by-carrier') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.carrier AS carrier,\n'
    sql << '       round(100.0 * count(CASE WHEN o.delivered_ts::DATE > o.promised_date THEN 1 END) / count(*), 2) AS late_pct\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasDateFrom) {
        sql << '  AND o.delivered_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.delivered_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCarrier && listHasValues(carrier)) {
        addInList(sql, params, carrier, 'AND o.carrier IN') { asDeclaredType('carrier', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY o.carrier\n'
    sql << 'ORDER BY late_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd20-chart-late-by-carrier', data)
}

// ─── Widget: chart_dd20-chart-boxplot-delivery-days-by-carrier (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd20-chart-boxplot-delivery-days-by-carrier') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.carrier AS carrier,\n'
    sql << '       date_diff(\'day\', o.order_ts::DATE, o.delivered_ts::DATE) AS delivery_days\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasDateFrom) {
        sql << '  AND o.delivered_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.delivered_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCarrier && listHasValues(carrier)) {
        addInList(sql, params, carrier, 'AND o.carrier IN') { asDeclaredType('carrier', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'ORDER BY o.carrier, delivery_days\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd20-chart-boxplot-delivery-days-by-carrier', data)
}

// ─── Widget: map_dd20-map-late-by-country (type=map, dataSource=sql) ───
if (!componentId || componentId == 'map_dd20-map-late-by-country') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT g.country AS country,\n'
    sql << '       CASE WHEN count(*) >= 60\n'
    sql << '            THEN round(100.0 * count(CASE WHEN o.delivered_ts::DATE > o.promised_date THEN 1 END) / count(*), 2)\n'
    sql << '       END AS late_pct\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasDateFrom) {
        sql << '  AND o.delivered_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.delivered_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCarrier && listHasValues(carrier)) {
        addInList(sql, params, carrier, 'AND o.carrier IN') { asDeclaredType('carrier', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY g.country\n'
    sql << 'ORDER BY g.country\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('map_dd20-map-late-by-country', data)
}

// ─── Widget: tabulator_dd20-table-late-orders (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd20-table-late-orders') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.order_id AS order_id,\n'
    sql << '       o.carrier AS carrier,\n'
    sql << '       g.country AS country,\n'
    sql << '       o.promised_date AS promised_date,\n'
    sql << '       o.delivered_ts::DATE AS delivered_date,\n'
    sql << '       date_diff(\'day\', o.promised_date, o.delivered_ts::DATE) AS days_late\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasDateFrom) {
        sql << '  AND o.delivered_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.delivered_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCarrier && listHasValues(carrier)) {
        addInList(sql, params, carrier, 'AND o.carrier IN') { asDeclaredType('carrier', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  AND o.delivered_ts::DATE > o.promised_date\n'
    sql << 'ORDER BY days_late DESC, o.delivered_ts DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd20-table-late-orders', data)
}

