// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def customerId = userVars?.get('customerId')?.toString()
def hasCustomerId = (customerId != null && !customerId.isEmpty())

// ─── Widget: detail_dd11-detail-customer-profile (type=detail, dataSource=script) ───
if (!componentId || componentId == 'detail_dd11-detail-customer-profile') {
    def detail_dd11_detail_customer_profile_data = { ->
        // Who the account is, for the top of the call: the record itself, where it is, and who owns it.
        dbSql.rows("""SELECT c.name AS customer,
               c.company_name AS company,
               c.customer_type AS type,
               c.segment AS segment,
               c.acquisition_channel AS acquired_through,
               c.signup_date AS customer_since,
               (SELECT count(*) FROM dash_demo.orders o WHERE o.customer_id = c.customer_id) AS orders,
               g.city AS city,
               g.country AS country,
               c.payment_terms_days AS payment_terms_days,
               c.credit_limit AS credit_limit,
               e.name AS account_manager
        FROM dash_demo.customers c
        JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
        LEFT JOIN dash_demo.employees e ON e.employee_id = c.account_manager_id
        WHERE c.customer_id = ?""", [customerId as Integer])
    }()
    ctx.reportData('detail_dd11-detail-customer-profile', detail_dd11_detail_customer_profile_data)
}

// ─── Widget: number_lifetime_revenue_revenue (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_lifetime_revenue_revenue') {
    def number_lifetime_revenue_revenue_data = { ->
        // Everything the account has bought that was not cancelled.
        dbSql.rows("""SELECT round(sum(o.total_amount), 2) AS lifetime_revenue
        FROM dash_demo.orders o
        WHERE o.status <> 'cancelled'
          AND o.customer_id = ?""", [customerId as Integer])
    }()
    ctx.reportData('number_lifetime_revenue_revenue', number_lifetime_revenue_revenue_data)
}

// ─── Widget: number_open_invoices_invoices (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_open_invoices_invoices') {
    def number_open_invoices_invoices_data = { ->
        // The money owed: issued and not settled.
        dbSql.rows("""SELECT count(*) AS open_invoices
        FROM dash_demo.invoices
        WHERE status IN ('open', 'overdue', 'partially_paid')
          AND customer_id = ?""", [customerId as Integer])
    }()
    ctx.reportData('number_open_invoices_invoices', number_open_invoices_invoices_data)
}

// ─── Widget: number_tickets_not_closed_closed (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_tickets_not_closed_closed') {
    def number_tickets_not_closed_closed_data = { ->
        // Still on the account: open, pending, or resolved and not yet closed out.
        dbSql.rows("""SELECT count(*) AS tickets_not_closed
        FROM dash_demo.support_tickets
        WHERE status <> 'closed'
          AND customer_id = ?""", [customerId as Integer])
    }()
    ctx.reportData('number_tickets_not_closed_closed', number_tickets_not_closed_closed_data)
}

// ─── Widget: number_care_plan_mrr_mrr (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_care_plan_mrr_mrr') {
    def number_care_plan_mrr_mrr_data = { ->
        // What the account pays every month for its care plan, if it has one.
        dbSql.rows("""SELECT round(coalesce(sum(mrr), 0), 2) AS care_plan_mrr
        FROM dash_demo.subscriptions
        WHERE cancel_date IS NULL
          AND customer_id = ?""", [customerId as Integer])
    }()
    ctx.reportData('number_care_plan_mrr_mrr', number_care_plan_mrr_mrr_data)
}

// ─── Widget: chart_dd11-chart-orders-per-month (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd11-chart-orders-per-month') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT date_trunc(\'month\', o.order_ts) AS month,\n'
    sql << '       count(*) AS orders,\n'
    sql << '       round(sum(o.total_amount), 2) AS revenue\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasCustomerId) {
        sql << '  AND o.customer_id = ?\n'
        params << asDeclaredType('customerId', 'Integer', customerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd11-chart-orders-per-month', data)
}

// ─── Widget: chart_dd11-chart-spend-by-category (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd11-chart-spend-by-category') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT p.category AS category,\n'
    sql << '       round(sum(l.line_amount), 2) AS spend\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasCustomerId) {
        sql << '  AND o.customer_id = ?\n'
        params << asDeclaredType('customerId', 'Integer', customerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY spend DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd11-chart-spend-by-category', data)
}

// ─── Widget: tabulator_dd11-table-last-20-orders (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd11-table-last-20-orders') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.order_id AS order_id,\n'
    sql << '       CAST(o.order_ts AS DATE) AS ordered,\n'
    sql << '       o.channel AS channel,\n'
    sql << '       o.status AS status,\n'
    sql << '       o.carrier AS carrier,\n'
    sql << '       o.promised_date AS promised,\n'
    sql << '       CAST(o.delivered_ts AS DATE) AS delivered,\n'
    sql << '       round(o.total_amount, 2) AS total_amount\n'
    sql << 'FROM dash_demo.orders o\n'
    if (hasCustomerId) {
        sql << 'WHERE o.customer_id = ?\n'
        params << asDeclaredType('customerId', 'Integer', customerId)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << 'ORDER BY o.order_ts DESC\n'
    sql << 'LIMIT 20\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd11-table-last-20-orders', data)
}

// ─── Widget: tabulator_dd11-table-tickets (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd11-table-tickets') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT t.ticket_id AS ticket_id,\n'
    sql << '       CAST(t.opened_ts AS DATE) AS opened,\n'
    sql << '       t.category AS category,\n'
    sql << '       t.priority AS priority,\n'
    sql << '       t.status AS status,\n'
    sql << '       t.channel AS channel,\n'
    sql << '       t.sla_breached AS sla_breached,\n'
    sql << '       t.csat_score AS csat\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    if (hasCustomerId) {
        sql << 'WHERE t.customer_id = ?\n'
        params << asDeclaredType('customerId', 'Integer', customerId)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << 'ORDER BY t.opened_ts DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd11-table-tickets', data)
}

