package com.flowkraft.exploredata.export;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.flowkraft.exploredata.export.DashboardDemos.Demo;

/**
 * The Gallery's cards and Athena's reference say what the index says, and nothing else.
 *
 * <p>Both are generated by {@link DashboardDemosGallery} from
 * {@code config/samples/dashboard-demos.json}. What is asserted here is the generated text itself:
 * that every demo has its own card, in the index's order, with the ids the e2e clicks, the two links
 * a reader follows, the dashboard the Canvas published, and the height the card reserves for it. That
 * the Gallery page in the tree still holds exactly this text is
 * {@code DashboardDemosExportParityTest}'s assertion, over the markers.
 */
class DashboardDemosGalleryTest {

	/** The areas of the catalogue, in the order the Gallery reads, each one contiguous. */
	private static final List<String> THE_AREAS = List.of(
			"A · The company at a glance",
			"B · Sales",
			"C · Customers",
			"D · Digital",
			"E · Finance",
			"F · People",
			"G · Operations",
			"H · The analyst's toolkit");

	@Test
	@DisplayName("Every demo of the index gets one card, in its area, with the ids the reader clicks")
	void everyDemoOfTheIndexGetsOneCard() throws Exception {

		List<Demo> demos = DashboardDemos.all();
		String cards = DashboardDemosGallery.cards(demos);
		List<String> wrong = new ArrayList<>();

		for (Demo demo : demos) {
			String id = demo.id();
			// Everything is asserted inside the demo's own card, because two demos may be the same
			// height or ask the same question, and a card is only right if it is right in one place.
			String card = cardOf(cards, id);
			if (card == null) {
				wrong.add(id + " has no card of its own");
				continue;
			}
			// The card, the two links and the dashboard: one of each, named the way the e2e names them.
			for (String needed : List.of(
					"<p class=\"card-area\" id=\"" + id + "-area\">",
					"<a id=\"lnkOpenAlone-" + id + "\" href=\"/dashboard/" + demo.reportId() + "\">",
					"<a id=\"lnkHowBuilt-" + id + "\" href=\""
							+ DashboardDemosGallery.field(demo, "howItWasBuiltUrl")
							+ "\" target=\"_blank\" rel=\"noopener\">",
					"<rb-dashboard report-id=\"" + demo.reportId()
							+ "\" api-base-url=\"/api\" lazy show-stories></rb-dashboard>",
					"style=\"min-height: " + demo.index().get("heightPx") + "px\""))
				if (count(card, needed) != 1)
					wrong.add(id + ": " + count(card, needed) + " of [" + needed + "]");

			// What the card says is the index's own words, as HTML text.
			for (String said : List.of("title", "question", "who", "decision", "finding"))
				if (!card.contains(DashboardDemosGallery.html(DashboardDemosGallery.field(demo, said))))
					wrong.add(id + " does not say its " + said);
		}

		assertTrue(wrong.isEmpty(), "the cards are not what the index says:\n" + String.join("\n", wrong));
		assertEquals(25, count(cards, "<div class=\"card\""), "one card per demo");
		assertEquals(25, count(cards, "<rb-dashboard "), "one dashboard per card");
	}

	@Test
	@DisplayName("The cards and the contents list run through the eight areas, each one contiguous")
	void theCardsRunThroughTheEightAreas() throws Exception {

		List<Demo> demos = DashboardDemos.all();
		Map<String, List<Demo>> byArea = DashboardDemosGallery.byArea(demos);

		assertEquals(THE_AREAS, new ArrayList<>(byArea.keySet()),
				"the areas of the index, in order: a demo out of its group would split an area in two");
		assertEquals(25, byArea.values().stream().mapToInt(List::size).sum(), "all 25 are in an area");

		// One heading per area, with the anchor the contents list links to, and in the same order.
		String cards = DashboardDemosGallery.cards(demos);
		String contents = DashboardDemosGallery.contents(demos);
		int reached = -1;
		Set<String> anchors = new LinkedHashSet<>();
		for (String area : THE_AREAS) {
			String anchor = DashboardDemosGallery.areaId(area);
			anchors.add(anchor);
			String heading = "<h2 class=\"area-heading\" id=\"" + anchor + "\">"
					+ DashboardDemosGallery.html(area) + "</h2>";
			assertEquals(1, count(cards, heading), "the cards' heading for " + area);
			assertEquals(1, count(contents, "<a href=\"#" + anchor + "\">"),
					"the contents list's entry for " + area);
			int at = cards.indexOf(heading);
			assertTrue(at > reached, area + " is out of order in the cards");
			reached = at;
		}
		assertEquals(THE_AREAS.size(), anchors.size(), "two areas cannot share one anchor");

		// Every demo is in the contents list too, linking to its own card.
		for (Demo demo : demos)
			assertEquals(1, count(contents, "<a href=\"#" + demo.id() + "\">"),
					demo.id() + " in the contents list");
	}

	@Test
	@DisplayName("Athena's reference names every demo, what it is made of and where to see it")
	void athenasReferenceNamesEveryDemo() throws Exception {

		List<Demo> demos = DashboardDemos.all();
		String reference = DashboardDemosGallery.liveDemos(demos);
		List<String> wrong = new ArrayList<>();

		for (Demo demo : demos) {
			if (count(reference, "(`" + demo.reportId() + "`)") != 1)
				wrong.add(demo.id() + " is not named once by its report id");
			if (!reference.contains("`/dashboard/" + DashboardDemosGallery.REPORT_ID + "#" + demo.id() + "`"))
				wrong.add(demo.id() + " does not say where it is in the gallery");
			if (!reference.contains(DashboardDemosGallery.field(demo, "howItWasBuiltUrl")))
				wrong.add(demo.id() + " does not say how it was built");

			// The tiles are read off the canvas, so the reference cannot describe a page the product
			// does not hold: every demo has at least one tile a reader reads, and the count is the
			// canvas's own, minus its title.
			String tiles = DashboardDemosGallery.tiles(demo);
			if ("none".equals(tiles))
				wrong.add(demo.id() + " is said to have no tile at all");
			if (tiles.contains("text") || tiles.contains("divider"))
				wrong.add(demo.id() + " counts its title as a tile: " + tiles);

			// The filters are the demo's own parameters, every one of them, by the name a story sets:
			// this is what the agent copies when it builds a filter bar of its own.
			String filters = DashboardDemosGallery.filters(demo);
			for (Map<String, Object> parameter : demo.parameters())
				if (!filters.contains("`" + parameter.get("id") + "`"))
					wrong.add(demo.id() + " does not offer " + parameter.get("id") + ": " + filters);
			if ("none".equals(filters))
				wrong.add(demo.id() + " is said to have no filter, and every demo has one");
		}

		for (String area : THE_AREAS)
			if (count(reference, "\n## " + area + "\n") != 1)
				wrong.add("the reference has no section for " + area);

		assertTrue(wrong.isEmpty(), "Athena's reference is not what the index says:\n"
				+ String.join("\n", wrong));
	}

	@Test
	@DisplayName("A card that drifts from the index is found, and a missing marker is refused")
	void aCardThatDriftsIsFound() throws Exception {

		// The comparison the parity test makes, made here on a page held in memory: what is between
		// the markers is replaced by what the index says, and a hand edit inside them shows up.
		List<Demo> demos = DashboardDemos.all();
		String page = "<div class=\"root\">\n  " + DashboardDemosGallery.CARDS_BEGIN + "\n"
				+ DashboardDemosGallery.cards(demos) + "\n  " + DashboardDemosGallery.CARDS_END
				+ "\n</div>\n";
		assertEquals(DashboardDemosGallery.cards(demos) + "\n  ",
				DashboardDemosGallery.between(page, DashboardDemosGallery.CARDS_BEGIN,
						DashboardDemosGallery.CARDS_END).substring(1),
				"the markers hold exactly the generated cards");

		String handEdited = page.replace("Executive Overview", "Executive Overview (old name)");
		assertTrue(!DashboardDemosGallery.between(handEdited, DashboardDemosGallery.CARDS_BEGIN,
				DashboardDemosGallery.CARDS_END).contains(">Executive Overview</h3>"),
				"a renamed card is no longer the index's");

		assertEquals(null, DashboardDemosGallery.between("<div>nothing marked</div>",
				DashboardDemosGallery.CARDS_BEGIN, DashboardDemosGallery.CARDS_END),
				"a page without the markers has no generated block");
	}

	/** One demo's card, from its opening div to the next one's, or null when it has none. */
	private static String cardOf(String cards, String id) {
		String opening = "<div class=\"card\" id=\"" + id + "\">";
		int from = cards.indexOf(opening);
		if (from < 0 || count(cards, opening) != 1)
			return null;
		int to = cards.indexOf("<div class=\"card\"", from + opening.length());
		return to < 0 ? cards.substring(from) : cards.substring(from, to);
	}

	private static int count(String text, String part) {
		int found = 0;
		for (int at = text.indexOf(part); at >= 0; at = text.indexOf(part, at + part.length()))
			found++;
		return found;
	}
}
