// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def minAmount = userVars?.get('minAmount')?.toString()
def hasMinAmount = (minAmount != null && !minAmount.isEmpty())
def accountManagerId = userVars?.get('accountManagerId')?.toString()
def hasAccountManagerId = (accountManagerId != null && !accountManagerId.isEmpty())

// ─── Widget: number_overdue_90_plus_plus (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_overdue_90_plus_plus') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(coalesce(sum(i.amount + i.tax_amount), 0), 2) AS overdue_90_plus\n'
    sql << 'FROM dash_demo.invoices i\n'
    sql << 'JOIN dash_demo.customers c ON c.customer_id = i.customer_id\n'
    sql << 'WHERE i.status IN (\'open\', \'overdue\', \'partially_paid\')\n'
    if (hasMinAmount) {
        sql << '  AND i.amount + i.tax_amount >= ?\n'
        params << asDeclaredType('minAmount', 'Double', minAmount)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasAccountManagerId) {
        sql << '  AND c.account_manager_id = ?\n'
        params << asDeclaredType('accountManagerId', 'Integer', accountManagerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND i.due_date < (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 90 DAY\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_overdue_90_plus_plus', data)
}

// ─── Widget: gauge_current_not_overdue_overdue (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_current_not_overdue_overdue') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(CASE WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a)\n'
    sql << '                      THEN i.amount + i.tax_amount ELSE 0 END)\n'
    sql << '             / sum(i.amount + i.tax_amount), 4) AS current_not_overdue\n'
    sql << 'FROM dash_demo.invoices i\n'
    sql << 'JOIN dash_demo.customers c ON c.customer_id = i.customer_id\n'
    sql << 'WHERE i.status IN (\'open\', \'overdue\', \'partially_paid\')\n'
    if (hasMinAmount) {
        sql << '  AND i.amount + i.tax_amount >= ?\n'
        params << asDeclaredType('minAmount', 'Double', minAmount)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasAccountManagerId) {
        sql << '  AND c.account_manager_id = ?\n'
        params << asDeclaredType('accountManagerId', 'Integer', accountManagerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_current_not_overdue_overdue', data)
}

// ─── Widget: trend_month_dso (type=trend, dataSource=script) ───
if (!componentId || componentId == 'trend_month_dso') {
    def trend_month_dso_data = { ->
        // DSO per month: receivables still outstanding at the end of the month, over the credit sales of
        // the year to that day, times 365 days. Two sums read at 24 different days is not one grouped query,
        // which is why this widget asks it itself. It is a company number: the page's two filters pick whom
        // to call today and do not change how long the company waits to be paid.
        dbSql.rows("""WITH months AS (
          SELECT CAST(date_trunc('month', (SELECT a.as_of FROM dash_demo.as_of a))
                      - to_months(CAST(s.i AS INTEGER)) AS DATE) AS month
          FROM generate_series(0, 23) AS s(i)
        ),
        month_end AS (
          SELECT month,
                 CAST(least(month + to_months(1) - to_days(1),
                            (SELECT a.as_of FROM dash_demo.as_of a)) AS DATE) AS read_at
          FROM months
        )
        SELECT m.month AS month,
               round(365.0
                     * (SELECT sum(i.amount + i.tax_amount) FROM dash_demo.invoices i
                        WHERE i.issue_date <= m.read_at
                          AND (i.last_paid_date IS NULL OR i.last_paid_date > m.read_at))
                     / (SELECT sum(i.amount + i.tax_amount) FROM dash_demo.invoices i
                        WHERE i.issue_date > m.read_at - to_days(365)
                          AND i.issue_date <= m.read_at), 2) AS dso_days
        FROM month_end m
        ORDER BY m.month""", [])
    }()
    ctx.reportData('trend_month_dso', trend_month_dso_data)
}

// ─── Widget: number_customers_overdue_overdue (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_customers_overdue_overdue') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(DISTINCT i.customer_id) AS customers_overdue\n'
    sql << 'FROM dash_demo.invoices i\n'
    sql << 'JOIN dash_demo.customers c ON c.customer_id = i.customer_id\n'
    sql << 'WHERE i.status IN (\'open\', \'overdue\', \'partially_paid\')\n'
    if (hasMinAmount) {
        sql << '  AND i.amount + i.tax_amount >= ?\n'
        params << asDeclaredType('minAmount', 'Double', minAmount)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasAccountManagerId) {
        sql << '  AND c.account_manager_id = ?\n'
        params << asDeclaredType('accountManagerId', 'Integer', accountManagerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND i.due_date < (SELECT a.as_of FROM dash_demo.as_of a)\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_customers_overdue_overdue', data)
}

// ─── Widget: chart_dd14-chart-aging-buckets (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd14-chart-aging-buckets') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH aged AS (\n'
    sql << '  SELECT CASE WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a) THEN 0\n'
    sql << '              WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 30 DAY THEN 1\n'
    sql << '              WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 60 DAY THEN 2\n'
    sql << '              WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 90 DAY THEN 3\n'
    sql << '              ELSE 4 END AS ord,\n'
    sql << '         c.segment AS segment,\n'
    sql << '         i.amount + i.tax_amount AS owed\n'
    sql << '  FROM dash_demo.invoices i\n'
    sql << '  JOIN dash_demo.customers c ON c.customer_id = i.customer_id\n'
    sql << '  WHERE i.status IN (\'open\', \'overdue\', \'partially_paid\')\n'
    if (hasMinAmount) {
        sql << '    AND i.amount + i.tax_amount >= ?\n'
        params << asDeclaredType('minAmount', 'Double', minAmount)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasAccountManagerId) {
        sql << '    AND c.account_manager_id = ?\n'
        params << asDeclaredType('accountManagerId', 'Integer', accountManagerId)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    sql << ')\n'
    sql << 'SELECT CASE ord WHEN 0 THEN \'Current\' WHEN 1 THEN \'1-30 days\' WHEN 2 THEN \'31-60 days\'\n'
    sql << '         WHEN 3 THEN \'61-90 days\' ELSE \'90+ days\' END AS bucket,\n'
    sql << '       round(sum(owed), 2) AS owed,\n'
    sql << '       count(*) AS invoices\n'
    sql << 'FROM aged\n'
    sql << 'GROUP BY ord\n'
    sql << 'ORDER BY ord\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd14-chart-aging-buckets', data)
}

// ─── Widget: chart_dd14-chart-aging-by-segment (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd14-chart-aging-by-segment') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH aged AS (\n'
    sql << '  SELECT CASE WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a) THEN 0\n'
    sql << '              WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 30 DAY THEN 1\n'
    sql << '              WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 60 DAY THEN 2\n'
    sql << '              WHEN i.due_date >= (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 90 DAY THEN 3\n'
    sql << '              ELSE 4 END AS ord,\n'
    sql << '         c.segment AS segment,\n'
    sql << '         i.amount + i.tax_amount AS owed\n'
    sql << '  FROM dash_demo.invoices i\n'
    sql << '  JOIN dash_demo.customers c ON c.customer_id = i.customer_id\n'
    sql << '  WHERE i.status IN (\'open\', \'overdue\', \'partially_paid\')\n'
    if (hasMinAmount) {
        sql << '    AND i.amount + i.tax_amount >= ?\n'
        params << asDeclaredType('minAmount', 'Double', minAmount)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasAccountManagerId) {
        sql << '    AND c.account_manager_id = ?\n'
        params << asDeclaredType('accountManagerId', 'Integer', accountManagerId)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    sql << ')\n'
    sql << 'SELECT CASE ord WHEN 0 THEN \'Current\' WHEN 1 THEN \'1-30 days\' WHEN 2 THEN \'31-60 days\'\n'
    sql << '         WHEN 3 THEN \'61-90 days\' ELSE \'90+ days\' END AS bucket,\n'
    sql << '       segment AS segment,\n'
    sql << '       round(sum(owed), 2) AS owed\n'
    sql << 'FROM aged\n'
    sql << 'GROUP BY ord, segment\n'
    sql << 'ORDER BY ord, segment\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd14-chart-aging-by-segment', data)
}

// ─── Widget: chart_dd14-chart-top-10-overdue-customers (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd14-chart-top-10-overdue-customers') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT c.name AS customer,\n'
    sql << '       round(sum(i.amount + i.tax_amount), 2) AS owed\n'
    sql << 'FROM dash_demo.invoices i\n'
    sql << 'JOIN dash_demo.customers c ON c.customer_id = i.customer_id\n'
    sql << 'WHERE i.status IN (\'open\', \'overdue\', \'partially_paid\')\n'
    if (hasMinAmount) {
        sql << '  AND i.amount + i.tax_amount >= ?\n'
        params << asDeclaredType('minAmount', 'Double', minAmount)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasAccountManagerId) {
        sql << '  AND c.account_manager_id = ?\n'
        params << asDeclaredType('accountManagerId', 'Integer', accountManagerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND i.due_date < (SELECT a.as_of FROM dash_demo.as_of a)\n'
    sql << 'GROUP BY c.name\n'
    sql << 'ORDER BY owed DESC\n'
    sql << 'LIMIT 10\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd14-chart-top-10-overdue-customers', data)
}

// ─── Widget: tabulator_dd14-table-overdue-invoices (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd14-table-overdue-invoices') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT i.invoice_no AS invoice_no,\n'
    sql << '       c.name AS customer,\n'
    sql << '       i.issue_date AS issued,\n'
    sql << '       i.due_date AS due,\n'
    sql << '       CAST((SELECT a.as_of FROM dash_demo.as_of a) - i.due_date AS INTEGER) AS days_overdue,\n'
    sql << '       round(i.amount + i.tax_amount, 2) AS owed,\n'
    sql << '       i.status AS status\n'
    sql << 'FROM dash_demo.invoices i\n'
    sql << 'JOIN dash_demo.customers c ON c.customer_id = i.customer_id\n'
    sql << 'WHERE i.status IN (\'open\', \'overdue\', \'partially_paid\')\n'
    if (hasMinAmount) {
        sql << '  AND i.amount + i.tax_amount >= ?\n'
        params << asDeclaredType('minAmount', 'Double', minAmount)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasAccountManagerId) {
        sql << '  AND c.account_manager_id = ?\n'
        params << asDeclaredType('accountManagerId', 'Integer', accountManagerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND i.due_date < (SELECT a.as_of FROM dash_demo.as_of a)\n'
    sql << 'ORDER BY days_overdue DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd14-table-overdue-invoices', data)
}

