// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def year = userVars?.get('year')?.toString()
def hasYear = (year != null && !year.isEmpty())

// ─── Widget: trend_year_start_revenue (type=trend, dataSource=sql) ───
if (!componentId || componentId == 'trend_year_start_revenue') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT date_trunc(\'year\', o.order_ts) AS year_start,\n'
    sql << '       round(sum(o.total_amount), 2) AS revenue\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasYear) {
        sql << '  AND year(o.order_ts) >= year(least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a))) - 1\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasYear) {
        sql << '  AND CAST(o.order_ts AS DATE) <= CASE WHEN year(o.order_ts) = year(least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a))) THEN least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a)) ELSE least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a)) - INTERVAL 1 YEAR END\n'
        params << asDeclaredType('year', 'Date', year)
        params << asDeclaredType('year', 'Date', year)
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('trend_year_start_revenue', data)
}

// ─── Widget: progress_dd01-kpi-revenue-vs-target (type=progress, dataSource=sql) ───
if (!componentId || componentId == 'progress_dd01-kpi-revenue-vs-target') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round((SELECT sum(o.total_amount) FROM dash_demo.orders o\n'
    sql << '                WHERE o.status <> \'cancelled\'\n'
    if (hasYear) {
        sql << '                  AND year(o.order_ts) = year(CAST(? AS DATE)))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '                  AND 1=1\n'   // no value: this filter is off
    }
    sql << '       / (SELECT sum(t.revenue_target) FROM dash_demo.sales_targets t\n'
    if (hasYear) {
        sql << '          WHERE year(t.month) = year(CAST(? AS DATE))), 4) AS pct_of_target\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '          WHERE 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('progress_dd01-kpi-revenue-vs-target', data)
}

// ─── Widget: number_mrr_mrr (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_mrr_mrr') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(s.mrr), 2) AS mrr\n'
    sql << 'FROM dash_demo.subscriptions s\n'
    if (hasYear) {
        sql << 'WHERE s.start_date <= least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasYear) {
        sql << '  AND (s.cancel_date IS NULL OR s.cancel_date > least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a)))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_mrr_mrr', data)
}

// ─── Widget: number_dso_days_dso (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_dso_days_dso') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(365.0\n'
    sql << '       * (SELECT sum(i.amount + i.tax_amount) FROM dash_demo.invoices i\n'
    if (hasYear) {
        sql << '          WHERE i.issue_date <= least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '          WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasYear) {
        sql << '            AND (i.last_paid_date IS NULL OR i.last_paid_date > least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a))))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '            AND 1=1\n'   // no value: this filter is off
    }
    sql << '       / (SELECT sum(i.amount + i.tax_amount) FROM dash_demo.invoices i\n'
    if (hasYear) {
        sql << '          WHERE i.issue_date > least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a)) - INTERVAL 365 DAY\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '          WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasYear) {
        sql << '            AND i.issue_date <= least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a))), 2) AS dso_days\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '            AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_dso_days_dso', data)
}

// ─── Widget: gauge_on_time_pct_time (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_on_time_pct_time') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(1.0 * count(CASE WHEN CAST(o.delivered_ts AS DATE) <= o.promised_date THEN 1 END) / count(*), 4) AS on_time_pct\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.delivered_ts IS NOT NULL\n'
    if (hasYear) {
        sql << '  AND year(o.delivered_ts) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_on_time_pct_time', data)
}

// ─── Widget: number_headcount_headcount (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_headcount_headcount') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) AS headcount\n'
    sql << 'FROM dash_demo.employees e\n'
    if (hasYear) {
        sql << 'WHERE e.hire_date <= least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasYear) {
        sql << '  AND (e.termination_date IS NULL OR e.termination_date > least(make_date(year(CAST(? AS DATE)), 12, 31), (SELECT a.as_of FROM dash_demo.as_of a)))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_headcount_headcount', data)
}

// ─── Widget: number_gross_margin_pct_margin (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_gross_margin_pct_margin') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(l.line_amount - l.line_cost) / sum(l.line_amount), 4) AS gross_margin_pct\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o USING (order_id)\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasYear) {
        sql << '  AND year(o.order_ts) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_gross_margin_pct_margin', data)
}

// ─── Widget: gauge_sla_met_pct_met (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_sla_met_pct_met') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(1.0 * count(CASE WHEN NOT t.sla_breached THEN 1 END) / count(*), 4) AS sla_met_pct\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    if (hasYear) {
        sql << 'WHERE year(t.opened_ts) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_sla_met_pct_met', data)
}

// ─── Widget: chart_dd01-chart-revenue-vs-target (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd01-chart-revenue-vs-target') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT strftime(a.month, \'%Y-%m\') AS month,\n'
    sql << '       round(a.revenue, 2) AS revenue,\n'
    sql << '       round(t.revenue_target, 2) AS revenue_target\n'
    sql << 'FROM (SELECT date_trunc(\'month\', o.order_ts) AS month, sum(o.total_amount) AS revenue\n'
    sql << '      FROM dash_demo.orders o\n'
    sql << '      WHERE o.status <> \'cancelled\'\n'
    if (hasYear) {
        sql << '        AND year(o.order_ts) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '        AND 1=1\n'   // no value: this filter is off
    }
    sql << '      GROUP BY 1) a\n'
    sql << 'LEFT JOIN (SELECT s.month AS month, sum(s.revenue_target) AS revenue_target\n'
    sql << '           FROM dash_demo.sales_targets s\n'
    if (hasYear) {
        sql << '           WHERE year(s.month) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << '           WHERE 1=1\n'   // no value: this filter is off
    }
    sql << '           GROUP BY 1) t ON t.month = a.month\n'
    sql << 'ORDER BY a.month\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd01-chart-revenue-vs-target', data)
}

// ─── Widget: tabulator_dd01-table-off-target (type=tabulator, dataSource=script) ───
if (!componentId || componentId == 'tabulator_dd01-table-off-target') {
    def tabulator_dd01_table_off_target_data = { ->
        // One row per area: the KPI the board judges it on, its target from kpi_targets, and on or off
        // track. Ten KPIs are ten different questions, which is why this widget asks them itself instead of
        // being one query.
        def selectedYear = (year && year.length() >= 4) ? (year.substring(0, 4) as Integer)
                : (dbSql.firstRow("SELECT year(as_of) AS y FROM dash_demo.as_of").y as Integer)
        
        // The day the year is read at: its last day, or the data's today while the year is still running.
        def cutoff = dbSql.firstRow("SELECT least(make_date(?, 12, 31), (SELECT as_of FROM dash_demo.as_of)) AS d",
                [selectedYear]).d
        
        def one = { String sql, List binds -> def row = dbSql.firstRow(sql, binds); row == null ? null : row[0] }
        
        // Revenue against plan, per region, from the monthly targets.
        def attainment = [:]
        dbSql.eachRow("""SELECT t.region AS region,
               round(100.0 * sum(o.actual) / sum(t.revenue_target), 2) AS pct
        FROM dash_demo.sales_targets t
        LEFT JOIN (SELECT date_trunc('month', o.order_ts) AS m, g.region AS region, sum(o.total_amount) AS actual
                   FROM dash_demo.orders o
                   JOIN dash_demo.geo_cities g USING (city_id)
                   WHERE o.status <> 'cancelled'
                   GROUP BY 1, 2) o ON o.m = t.month AND o.region = t.region
        WHERE year(t.month) = ?
        GROUP BY 1""", [selectedYear]) { row -> attainment[row.region] = row.pct }
        
        def grossMargin = one("""SELECT round(100.0 * sum(l.line_amount - l.line_cost) / sum(l.line_amount), 2)
        FROM dash_demo.order_lines l
        JOIN dash_demo.orders o USING (order_id)
        WHERE o.status <> 'cancelled'
          AND year(o.order_ts) = ?""", [selectedYear])
        
        def dso = one("""SELECT round(365.0
               * (SELECT sum(amount + tax_amount) FROM dash_demo.invoices
                  WHERE issue_date <= ? AND (last_paid_date IS NULL OR last_paid_date > ?))
               / (SELECT sum(amount + tax_amount) FROM dash_demo.invoices
                  WHERE issue_date > ? - INTERVAL 365 DAY AND issue_date <= ?), 2)""",
                [cutoff, cutoff, cutoff, cutoff])
        
        def onTime = one("""SELECT round(100.0 * count(CASE WHEN CAST(delivered_ts AS DATE) <= promised_date THEN 1 END) / count(*), 2)
        FROM dash_demo.orders
        WHERE delivered_ts IS NOT NULL
          AND year(delivered_ts) = ?""", [selectedYear])
        
        def slaMet = one("""SELECT round(100.0 * count(CASE WHEN NOT sla_breached THEN 1 END) / count(*), 2)
        FROM dash_demo.support_tickets
        WHERE year(opened_ts) = ?""", [selectedYear])
        
        // Churn: the average of the months in which a subscription was cancelled, each against the
        // subscriptions that were live when that month began.
        def churn = one("""SELECT round(avg(pct), 2) FROM (
            SELECT 100.0 * count(*) /
                   (SELECT count(*) FROM dash_demo.subscriptions s2
                    WHERE s2.start_date < m AND (s2.cancel_date IS NULL OR s2.cancel_date >= m)) AS pct
            FROM (SELECT DISTINCT date_trunc('month', cancel_date) AS m FROM dash_demo.subscriptions
                  WHERE year(cancel_date) = ?) months
            JOIN dash_demo.subscriptions s ON date_trunc('month', s.cancel_date) = months.m
            GROUP BY m)""", [selectedYear])
        
        // Attrition: the people who left over the twelve months to the cutoff, against the people employed at it.
        def attrition = one("""SELECT round(100.0 * (SELECT count(*) FROM dash_demo.employees
               WHERE termination_date >= ? - INTERVAL 365 DAY AND termination_date <= ?)
             / (SELECT count(*) FROM dash_demo.employees
                WHERE hire_date <= ? AND (termination_date IS NULL OR termination_date > ?)), 2)""",
                [cutoff, cutoff, cutoff, cutoff])
        
        def measured = [
            'EMEA|revenue_vs_plan'      : attainment['EMEA'],
            'NA|revenue_vs_plan'        : attainment['NA'],
            'APAC|revenue_vs_plan'      : attainment['APAC'],
            'LATAM|revenue_vs_plan'     : attainment['LATAM'],
            'Company|gross_margin'      : grossMargin,
            'Finance|days_sales_outstanding': dso,
            'Operations|on_time_delivery'   : onTime,
            'Support|sla_met'           : slaMet,
            'Company|monthly_churn'     : churn,
            'People|yearly_attrition'   : attrition,
        ]
        
        def rows = []
        dbSql.eachRow("SELECT area, kpi, target, direction, unit FROM dash_demo.kpi_targets") { target ->
            def actual = measured[target.area + '|' + target.kpi]
            def higherIsBetter = target.direction == 'higher_is_better'
            def onTrack = actual == null ? null
                    : (higherIsBetter ? actual >= target.target : actual <= target.target)
            rows << [
                'Area'   : target.area,
                'KPI'    : target.kpi.replace('_', ' '),
                'Actual' : actual,
                'Target' : target.target,
                'Unit'   : target.unit,
                'Status' : onTrack == null ? 'no reading' : (onTrack ? 'on track' : 'off target'),
            ]
        }
        
        // The areas off target first: they are what the reader came for.
        rows.sort { a, b -> (a.Status == 'off target' ? 0 : 1) <=> (b.Status == 'off target' ? 0 : 1) ?: a.Area <=> b.Area }
        rows
    }()
    ctx.reportData('tabulator_dd01-table-off-target', tabulator_dd01_table_off_target_data)
}

