// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def priority = userVars?.get('priority')?.toString()
def hasPriority = (priority != null && !priority.isEmpty())
def team = userVars?.get('team')?.toString()
def hasTeam = (team != null && !team.isEmpty())

// ─── Widget: number_opentickets_tickets (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_opentickets_tickets') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  COUNT(CASE WHEN (dash_demo.support_tickets.status IN (\'open\', \'pending\')) THEN 1 END) AS "OpenTickets"\n'
    sql << 'FROM dash_demo.support_tickets\n'
    sql << 'LEFT JOIN dash_demo.support_agents ON dash_demo.support_tickets.agent_id = dash_demo.support_agents.agent_id\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'WHERE dash_demo.support_tickets.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'WHERE 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND dash_demo.support_agents.team = ?\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_opentickets_tickets', data)
}

// ─── Widget: number_opened_last_7_days_days (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_opened_last_7_days_days') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) AS opened_last_7_days\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'AND t.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND t.opened_ts > (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 7 DAY\n'
    sql << '  AND t.opened_ts < (SELECT a.as_of FROM dash_demo.as_of a) + INTERVAL 1 DAY\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_opened_last_7_days_days', data)
}

// ─── Widget: number_avgfirstresponseminutes_response (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_avgfirstresponseminutes_response') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  CAST(AVG(CAST(date_diff(\'minute\', dash_demo.support_tickets.opened_ts, dash_demo.support_tickets.first_response_ts) AS DECIMAL(31,4))) AS DECIMAL(31,4)) AS "AvgFirstResponseMinutes"\n'
    sql << 'FROM dash_demo.support_tickets\n'
    sql << 'LEFT JOIN dash_demo.support_agents ON dash_demo.support_tickets.agent_id = dash_demo.support_agents.agent_id\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'WHERE dash_demo.support_tickets.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'WHERE 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND dash_demo.support_agents.team = ?\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_avgfirstresponseminutes_response', data)
}

// ─── Widget: gauge_sla_met_rate_met (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_sla_met_rate_met') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(count(CASE WHEN NOT t.sla_breached THEN 1 END) / count(*)::DOUBLE, 4) AS sla_met_rate\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'AND t.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_sla_met_rate_met', data)
}

// ─── Widget: pivot_dd21-pivot-tickets-weekday-hour (type=pivot, dataSource=sql) ───
if (!componentId || componentId == 'pivot_dd21-pivot-tickets-weekday-hour') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT CAST(isodow(t.opened_ts) AS VARCHAR) || \' \' || strftime(t.opened_ts, \'%a\') AS weekday,\n'
    sql << '       lpad(CAST(hour(t.opened_ts) AS VARCHAR), 2, \'0\') AS hour_of_day,\n'
    sql << '       count(*) AS tickets\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'AND t.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1, 2\n'
    sql << 'ORDER BY 1, 2\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('pivot_dd21-pivot-tickets-weekday-hour', data)
}

// ─── Widget: chart_dd21-chart-created-vs-resolved-per-week (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd21-chart-created-vs-resolved-per-week') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT week,\n'
    sql << '       sum(created) AS created,\n'
    sql << '       sum(resolved) AS resolved\n'
    sql << 'FROM (\n'
    sql << '  SELECT date_trunc(\'week\', t.opened_ts)::DATE AS week, 1 AS created, 0 AS resolved\n'
    sql << '  FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'AND t.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '    AND t.opened_ts >= (SELECT date_trunc(\'week\', min(t2.opened_ts)) + INTERVAL 7 DAY FROM dash_demo.support_tickets t2)\n'
    sql << '    AND t.opened_ts < date_trunc(\'week\', (SELECT a.as_of FROM dash_demo.as_of a))\n'
    sql << '  UNION ALL\n'
    sql << '  SELECT date_trunc(\'week\', t.resolved_ts)::DATE AS week, 0 AS created, 1 AS resolved\n'
    sql << '  FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'AND t.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '    AND t.resolved_ts IS NOT NULL\n'
    sql << '    AND t.resolved_ts >= (SELECT date_trunc(\'week\', min(t2.opened_ts)) + INTERVAL 7 DAY FROM dash_demo.support_tickets t2)\n'
    sql << '    AND t.resolved_ts < date_trunc(\'week\', (SELECT a.as_of FROM dash_demo.as_of a))\n'
    sql << ')\n'
    sql << 'GROUP BY week\n'
    sql << 'ORDER BY week\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd21-chart-created-vs-resolved-per-week', data)
}

// ─── Widget: chart_dd21-chart-open-backlog-by-priority (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd21-chart-open-backlog-by-priority') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT CASE WHEN date_diff(\'day\', t.opened_ts, (SELECT a.as_of FROM dash_demo.as_of a)) <= 2 THEN \'1 up to 2 days\'\n'
    sql << '            WHEN date_diff(\'day\', t.opened_ts, (SELECT a.as_of FROM dash_demo.as_of a)) <= 7 THEN \'2 3 to 7 days\'\n'
    sql << '            WHEN date_diff(\'day\', t.opened_ts, (SELECT a.as_of FROM dash_demo.as_of a)) <= 30 THEN \'3 8 to 30 days\'\n'
    sql << '            ELSE \'4 over 30 days\' END AS age_band,\n'
    sql << '       t.priority AS priority,\n'
    sql << '       count(*) AS open_tickets\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'WHERE true\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'AND t.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND t.status IN (\'open\', \'pending\')\n'
    sql << 'GROUP BY 1, 2\n'
    sql << 'ORDER BY 1, 2\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd21-chart-open-backlog-by-priority', data)
}

// ─── Widget: tabulator_dd21-table-open-urgent-and-high (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd21-table-open-urgent-and-high') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT t.ticket_id AS ticket_id,\n'
    sql << '       t.priority AS priority,\n'
    sql << '       t.status AS status,\n'
    sql << '       t.channel AS channel,\n'
    sql << '       t.category AS category,\n'
    sql << '       sa.name AS agent,\n'
    sql << '       t.opened_ts::DATE AS opened_date,\n'
    sql << '       date_diff(\'day\', t.opened_ts, (SELECT a.as_of FROM dash_demo.as_of a)) AS days_waiting\n'
    sql << 'FROM dash_demo.support_tickets t\n'
    sql << 'LEFT JOIN dash_demo.support_agents sa ON sa.agent_id = t.agent_id\n'
    sql << 'WHERE true\n'
    if (hasPriority && listHasValues(priority)) {
        addInList(sql, params, priority, 'AND t.priority IN') { asDeclaredType('priority', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasTeam) {
        sql << '  AND t.agent_id IN (SELECT sa.agent_id FROM dash_demo.support_agents sa WHERE sa.team = ?)\n'
        params << asDeclaredType('team', 'String', team)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND t.status IN (\'open\', \'pending\')\n'
    sql << '  AND t.priority IN (\'urgent\', \'high\')\n'
    sql << 'ORDER BY days_waiting DESC, t.ticket_id\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd21-table-open-urgent-and-high', data)
}

