// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.DateParameters
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// The day after a date: where a range of whole days ends, so that its last day counts
// in full. An empty value stays empty.
def dayAfter = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return DateParameters.nextDay(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def dateFrom = userVars?.get('dateFrom')?.toString()
def hasDateFrom = (dateFrom != null && !dateFrom.isEmpty())
def dateTo = userVars?.get('dateTo')?.toString()
def hasDateTo = (dateTo != null && !dateTo.isEmpty())
def category = userVars?.get('category')?.toString()
def hasCategory = (category != null && !category.isEmpty())
def dateTo__next_day = dayAfter('dateTo', 'Date', dateTo)
def hasDateTo__next_day = (dateTo__next_day != null && !dateTo__next_day.isEmpty())

// ─── Widget: number_marginpct_margin (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_marginpct_margin') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  1.0 * ((CAST(SUM(CASE WHEN (dash_demo.orders.status <> \'cancelled\') THEN dash_demo.order_lines.line_amount END) AS DECIMAL(31,4))) - (CAST(SUM(CASE WHEN (dash_demo.orders.status <> \'cancelled\') THEN dash_demo.order_lines.line_cost END) AS DECIMAL(31,4)))) / NULLIF((CAST(SUM(CASE WHEN (dash_demo.orders.status <> \'cancelled\') THEN dash_demo.order_lines.line_amount END) AS DECIMAL(31,4))), 0) AS "MarginPct"\n'
    sql << 'FROM dash_demo.order_lines\n'
    sql << 'LEFT JOIN dash_demo.orders ON dash_demo.order_lines.order_id = dash_demo.orders.order_id\n'
    sql << 'LEFT JOIN dash_demo.products ON dash_demo.order_lines.product_id = dash_demo.products.product_id\n'
    if (hasDateTo__next_day) {
        sql << 'WHERE dash_demo.orders.order_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasDateFrom) {
        sql << '  AND dash_demo.orders.order_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory) {
        sql << '  AND dash_demo.products.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_marginpct_margin', data)
}

// ─── Widget: number_grossprofit_profit (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_grossprofit_profit') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  (CAST(SUM(CASE WHEN (dash_demo.orders.status <> \'cancelled\') THEN dash_demo.order_lines.line_amount END) AS DECIMAL(31,4))) - (CAST(SUM(CASE WHEN (dash_demo.orders.status <> \'cancelled\') THEN dash_demo.order_lines.line_cost END) AS DECIMAL(31,4))) AS "GrossProfit"\n'
    sql << 'FROM dash_demo.order_lines\n'
    sql << 'LEFT JOIN dash_demo.orders ON dash_demo.order_lines.order_id = dash_demo.orders.order_id\n'
    sql << 'LEFT JOIN dash_demo.products ON dash_demo.order_lines.product_id = dash_demo.products.product_id\n'
    if (hasDateTo__next_day) {
        sql << 'WHERE dash_demo.orders.order_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasDateFrom) {
        sql << '  AND dash_demo.orders.order_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory) {
        sql << '  AND dash_demo.products.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_grossprofit_profit', data)
}

// ─── Widget: number_discounts_given_given (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_discounts_given_given') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(l.qty * l.unit_price * l.discount_pct / 100.0), 2) AS discounts_given\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasDateFrom) {
        sql << '  AND o.order_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.order_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory) {
        sql << '  AND p.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_discounts_given_given', data)
}

// ─── Widget: chart_dd16-chart-revenue-and-margin-per-month (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd16-chart-revenue-and-margin-per-month') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT strftime(date_trunc(\'month\', o.order_ts), \'%Y-%m\') AS month,\n'
    sql << '       round(sum(l.line_amount), 2) AS revenue,\n'
    sql << '       round(100.0 * sum(l.line_amount - l.line_cost) / sum(l.line_amount), 2) AS margin_pct\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasDateFrom) {
        sql << '  AND o.order_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.order_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory) {
        sql << '  AND p.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY month\n'
    sql << 'ORDER BY month\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd16-chart-revenue-and-margin-per-month', data)
}

// ─── Widget: chart_dd16-chart-waterfall-list-price-to-gross-profit (type=chart, dataSource=script) ───
if (!componentId || componentId == 'chart_dd16-chart-waterfall-list-price-to-gross-profit') {
    def chart_dd16_chart_waterfall_list_price_to_gross_profit_data = { ->
        // Where the money goes between the price on the label and the profit left: the discount given away,
        // then what the goods cost. The three steps run from the running total before them, so the level the
        // last one lands on is the gross profit the r1 tile shows.
        dbSql.rows("""WITH scope AS (
          SELECT l.qty * l.unit_price AS list_amount,
                 l.qty * l.unit_price * l.discount_pct / 100.0 AS discount_amount,
                 l.line_amount AS revenue,
                 l.line_cost AS cost
          FROM dash_demo.order_lines l
          JOIN dash_demo.orders o ON o.order_id = l.order_id
          JOIN dash_demo.products p ON p.product_id = l.product_id
          WHERE o.status <> 'cancelled'
            AND o.order_ts >= CAST(? AS DATE)
            AND o.order_ts < CAST(? AS DATE) + INTERVAL 1 DAY
            AND (? = '' OR p.category = ?)
        )
        SELECT 1 AS ord, 'Revenue at list price' AS step, round(sum(list_amount), 2) AS amount FROM scope
        UNION ALL SELECT 2, 'Discounts', -round(sum(discount_amount), 2) FROM scope
        UNION ALL SELECT 3, 'Cost of goods sold', -round(sum(cost), 2) FROM scope
        ORDER BY ord""", [dateFrom, dateTo, category, category])
    }()
    ctx.reportData('chart_dd16-chart-waterfall-list-price-to-gross-profit', chart_dd16_chart_waterfall_list_price_to_gross_profit_data)
}

// ─── Widget: pivot_dd16-pivot-margin-by-category-quarter (type=pivot, dataSource=visual) ───
if (!componentId || componentId == 'pivot_dd16-pivot-margin-by-category-quarter') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  dash_demo.products.category AS "Category",\n'
    sql << '  CAST(DATE_TRUNC(\'quarter\', dash_demo.orders.order_ts) AS DATE) AS "OrderedAt",\n'
    sql << '  1.0 * ((CAST(SUM(CASE WHEN (dash_demo.orders.status <> \'cancelled\') THEN dash_demo.order_lines.line_amount END) AS DECIMAL(31,4))) - (CAST(SUM(CASE WHEN (dash_demo.orders.status <> \'cancelled\') THEN dash_demo.order_lines.line_cost END) AS DECIMAL(31,4)))) / NULLIF((CAST(SUM(CASE WHEN (dash_demo.orders.status <> \'cancelled\') THEN dash_demo.order_lines.line_amount END) AS DECIMAL(31,4))), 0) AS "MarginPct"\n'
    sql << 'FROM dash_demo.order_lines\n'
    sql << 'LEFT JOIN dash_demo.orders ON dash_demo.order_lines.order_id = dash_demo.orders.order_id\n'
    sql << 'LEFT JOIN dash_demo.products ON dash_demo.order_lines.product_id = dash_demo.products.product_id\n'
    if (hasDateTo__next_day) {
        sql << 'WHERE dash_demo.orders.order_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasDateFrom) {
        sql << '  AND dash_demo.orders.order_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory) {
        sql << '  AND dash_demo.products.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY\n'
    sql << '  dash_demo.products.category,\n'
    sql << '  CAST(DATE_TRUNC(\'quarter\', dash_demo.orders.order_ts) AS DATE)\n'
    sql << 'ORDER BY\n'
    sql << '  "Category" ASC,\n'
    sql << '  "OrderedAt" ASC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('pivot_dd16-pivot-margin-by-category-quarter', data)
}

