// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def tableName = userVars?.get('tableName')?.toString()
def hasTableName = (tableName != null && !tableName.isEmpty())
def columnName = userVars?.get('columnName')?.toString()
def hasColumnName = (columnName != null && !columnName.isEmpty())

// ─── Widget: number_row_count_rows (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_row_count_rows') {
    def number_row_count_rows_data = { ->
        // Whitelisted, never trusted: the name must be a table of dash_demo before it goes
        // anywhere near a query, because it lands in FROM where no bind can carry it.
        if (!dbSql.firstRow("SELECT 1 FROM information_schema.tables WHERE table_schema = 'dash_demo' AND table_name = ?", [tableName])) return []
        dbSql.rows("""SELECT count(*) AS row_count
        FROM dash_demo.${tableName}""", [])
    }()
    ctx.reportData('number_row_count_rows', number_row_count_rows_data)
}

// ─── Widget: number_column_count_columns (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_column_count_columns') {
    def number_column_count_columns_data = { ->
        // Whitelisted, never trusted: the name must be a table of dash_demo before it goes
        // anywhere near a query, because it lands in FROM where no bind can carry it.
        if (!dbSql.firstRow("SELECT 1 FROM information_schema.tables WHERE table_schema = 'dash_demo' AND table_name = ?", [tableName])) return []
        dbSql.rows("""SELECT count(*) AS column_count
        FROM information_schema.columns
        WHERE table_schema = 'dash_demo'
          AND table_name = ?""", [tableName])
    }()
    ctx.reportData('number_column_count_columns', number_column_count_columns_data)
}

// ─── Widget: number_rows_added_days (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_rows_added_days') {
    def number_rows_added_days_data = { ->
        // Whitelisted, never trusted: the name must be a table of dash_demo before it goes
        // anywhere near a query, because it lands in FROM where no bind can carry it.
        if (!dbSql.firstRow("SELECT 1 FROM information_schema.tables WHERE table_schema = 'dash_demo' AND table_name = ?", [tableName])) return []
        // The first date or timestamp column whose name speaks of a beginning. A table with
        // none of them has no freshness to show, and the tile stays empty.
        def created = dbSql.firstRow("SELECT column_name FROM information_schema.columns WHERE table_schema = 'dash_demo' AND table_name = ? AND data_type IN ('DATE', 'TIMESTAMP') AND (column_name LIKE '%created%' OR column_name LIKE '%opened%' OR column_name LIKE '%signup%' OR column_name LIKE '%issue%' OR column_name LIKE '%order_ts%' OR column_name LIKE '%hire%' OR column_name LIKE '%period%' OR column_name LIKE '%started%') ORDER BY ordinal_position LIMIT 1", [tableName])?.column_name
        if (created == null) return []
        dbSql.rows("""SELECT count(*) AS rows_added
        FROM dash_demo.${tableName}
        WHERE ${created} >= (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 30 DAY
          AND ${created} <= (SELECT a.as_of FROM dash_demo.as_of a)""", [])
    }()
    ctx.reportData('number_rows_added_days', number_rows_added_days_data)
}

// ─── Widget: number_columns_with_nulls_nulls (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_columns_with_nulls_nulls') {
    def number_columns_with_nulls_nulls_data = { ->
        // Whitelisted, never trusted: the name must be a table of dash_demo before it goes
        // anywhere near a query, because it lands in FROM where no bind can carry it.
        if (!dbSql.firstRow("SELECT 1 FROM information_schema.tables WHERE table_schema = 'dash_demo' AND table_name = ?", [tableName])) return []
        dbSql.rows("""SELECT count(*) AS columns_with_nulls
        FROM (SUMMARIZE dash_demo.${tableName})
        WHERE null_percentage > 0""", [])
    }()
    ctx.reportData('number_columns_with_nulls_nulls', number_columns_with_nulls_nulls_data)
}

// ─── Widget: tabulator_dd23-table-column-profile (type=tabulator, dataSource=script) ───
if (!componentId || componentId == 'tabulator_dd23-table-column-profile') {
    def tabulator_dd23_table_column_profile_data = { ->
        // Whitelisted, never trusted: the name must be a table of dash_demo before it goes
        // anywhere near a query, because it lands in FROM where no bind can carry it.
        if (!dbSql.firstRow("SELECT 1 FROM information_schema.tables WHERE table_schema = 'dash_demo' AND table_name = ?", [tableName])) return []
        dbSql.rows("""SELECT s.column_name AS column_name,
               s.column_type AS column_type,
               CASE WHEN right(s.column_name, 3) = '_id' THEN 'key'
                    WHEN s.column_type IN ('DATE', 'TIMESTAMP') THEN 'when'
                    WHEN s.column_type = 'BOOLEAN' THEN 'flag'
                    WHEN s.column_name LIKE '%amount%' OR s.column_name LIKE '%price%'
                         OR s.column_name LIKE '%cost%' OR s.column_name LIKE '%pay%'
                         OR s.column_name LIKE '%qty%' OR s.column_name LIKE '%score%'
                         OR s.column_name LIKE '%limit%' OR s.column_name LIKE '%fee%' THEN 'measure'
                    ELSE 'attribute'
               END AS role_guessed_from_the_name,
               s.null_percentage AS null_percentage,
               s.approx_unique AS distinct_values_approx,
               s.min AS smallest,
               s.avg AS average,
               s.max AS largest
        FROM (SUMMARIZE dash_demo.${tableName}) s
        JOIN information_schema.columns c
          ON c.table_schema = 'dash_demo' AND c.table_name = ? AND c.column_name = s.column_name
        ORDER BY c.ordinal_position""", [tableName])
    }()
    ctx.reportData('tabulator_dd23-table-column-profile', tabulator_dd23_table_column_profile_data)
}

// ─── Widget: chart_dd23-chart-distribution (type=chart, dataSource=script) ───
if (!componentId || componentId == 'chart_dd23-chart-distribution') {
    def chart_dd23_chart_distribution_data = { ->
        // Whitelisted, never trusted: the name must be a table of dash_demo before it goes
        // anywhere near a query, because it lands in FROM where no bind can carry it.
        if (!dbSql.firstRow("SELECT 1 FROM information_schema.tables WHERE table_schema = 'dash_demo' AND table_name = ?", [tableName])) return []
        if (!dbSql.firstRow("SELECT 1 FROM information_schema.columns WHERE table_schema = 'dash_demo' AND table_name = ? AND column_name = ?", [tableName, columnName])) return []
        dbSql.rows("""WITH v AS (
          SELECT CAST(${columnName} AS VARCHAR) AS txt,
                 TRY_CAST(CAST(${columnName} AS VARCHAR) AS DOUBLE) AS num
          FROM dash_demo.${tableName}
        ),
        shape AS (
          SELECT count(txt) AS filled, count(num) AS numeric_rows,
                 count(DISTINCT txt) AS distinct_values,
                 min(num) AS lo, max(num) AS hi
          FROM v
        ),
        bucketed AS (
          SELECT CASE WHEN s.numeric_rows = s.filled AND s.distinct_values > 20
                      THEN least(19, CAST(floor((v.num - s.lo) / nullif(s.hi - s.lo, 0) * 20) AS INTEGER))
                 END AS bin,
                 v.txt AS txt, v.num AS num, s.lo AS lo, s.hi AS hi
          FROM v, shape s
          WHERE v.txt IS NOT NULL
        )
        SELECT CASE WHEN b.bin IS NULL THEN b.txt
                    ELSE printf('%.2f - %.2f',
                                b.lo + (b.hi - b.lo) * b.bin / 20.0,
                                b.lo + (b.hi - b.lo) * (b.bin + 1) / 20.0)
               END AS bucket,
               count(*) AS rows_in_bucket
        FROM bucketed b
        GROUP BY bucket, b.bin
        ORDER BY b.bin NULLS LAST, rows_in_bucket DESC, bucket
        LIMIT 20""", [])
    }()
    ctx.reportData('chart_dd23-chart-distribution', chart_dd23_chart_distribution_data)
}

