// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def year = userVars?.get('year')?.toString()
def hasYear = (year != null && !year.isEmpty())
def region = userVars?.get('region')?.toString()
def hasRegion = (region != null && !region.isEmpty())

// ─── Widget: progress_dd08-progress-emea (type=progress, dataSource=sql) ───
if (!componentId || componentId == 'progress_dd08-progress-emea') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(a.actual) / sum(t.revenue_target), 4) AS pct_of_target\n'
    sql << 'FROM dash_demo.sales_targets t\n'
    sql << 'LEFT JOIN (SELECT date_trunc(\'month\', o.order_ts) AS m,\n'
    sql << '                  g.region AS region,\n'
    sql << '                  sum(o.total_amount) AS actual\n'
    sql << '           FROM dash_demo.orders o\n'
    sql << '           JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '           WHERE o.status <> \'cancelled\'\n'
    sql << '           GROUP BY 1, 2\n'
    sql << '          ) a ON a.m = t.month AND a.region = t.region\n'
    if (hasYear) {
        sql << 'WHERE year(t.month) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << '  AND t.region = \'EMEA\'\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('progress_dd08-progress-emea', data)
}

// ─── Widget: progress_dd08-progress-na (type=progress, dataSource=sql) ───
if (!componentId || componentId == 'progress_dd08-progress-na') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(a.actual) / sum(t.revenue_target), 4) AS pct_of_target\n'
    sql << 'FROM dash_demo.sales_targets t\n'
    sql << 'LEFT JOIN (SELECT date_trunc(\'month\', o.order_ts) AS m,\n'
    sql << '                  g.region AS region,\n'
    sql << '                  sum(o.total_amount) AS actual\n'
    sql << '           FROM dash_demo.orders o\n'
    sql << '           JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '           WHERE o.status <> \'cancelled\'\n'
    sql << '           GROUP BY 1, 2\n'
    sql << '          ) a ON a.m = t.month AND a.region = t.region\n'
    if (hasYear) {
        sql << 'WHERE year(t.month) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << '  AND t.region = \'NA\'\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('progress_dd08-progress-na', data)
}

// ─── Widget: progress_dd08-progress-apac (type=progress, dataSource=sql) ───
if (!componentId || componentId == 'progress_dd08-progress-apac') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(a.actual) / sum(t.revenue_target), 4) AS pct_of_target\n'
    sql << 'FROM dash_demo.sales_targets t\n'
    sql << 'LEFT JOIN (SELECT date_trunc(\'month\', o.order_ts) AS m,\n'
    sql << '                  g.region AS region,\n'
    sql << '                  sum(o.total_amount) AS actual\n'
    sql << '           FROM dash_demo.orders o\n'
    sql << '           JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '           WHERE o.status <> \'cancelled\'\n'
    sql << '           GROUP BY 1, 2\n'
    sql << '          ) a ON a.m = t.month AND a.region = t.region\n'
    if (hasYear) {
        sql << 'WHERE year(t.month) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << '  AND t.region = \'APAC\'\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('progress_dd08-progress-apac', data)
}

// ─── Widget: progress_dd08-progress-latam (type=progress, dataSource=sql) ───
if (!componentId || componentId == 'progress_dd08-progress-latam') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(a.actual) / sum(t.revenue_target), 4) AS pct_of_target\n'
    sql << 'FROM dash_demo.sales_targets t\n'
    sql << 'LEFT JOIN (SELECT date_trunc(\'month\', o.order_ts) AS m,\n'
    sql << '                  g.region AS region,\n'
    sql << '                  sum(o.total_amount) AS actual\n'
    sql << '           FROM dash_demo.orders o\n'
    sql << '           JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '           WHERE o.status <> \'cancelled\'\n'
    sql << '           GROUP BY 1, 2\n'
    sql << '          ) a ON a.m = t.month AND a.region = t.region\n'
    if (hasYear) {
        sql << 'WHERE year(t.month) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << '  AND t.region = \'LATAM\'\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('progress_dd08-progress-latam', data)
}

// ─── Widget: chart_dd08-chart-monthly-revenue-vs-target (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd08-chart-monthly-revenue-vs-target') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT strftime(t.month, \'%Y-%m\') AS month,\n'
    sql << '       round(sum(a.actual), 2) AS actual,\n'
    sql << '       round(sum(t.revenue_target), 2) AS revenue_target\n'
    sql << 'FROM dash_demo.sales_targets t\n'
    sql << 'LEFT JOIN (SELECT date_trunc(\'month\', o.order_ts) AS m,\n'
    sql << '                  g.region AS region,\n'
    sql << '                  sum(o.total_amount) AS actual\n'
    sql << '           FROM dash_demo.orders o\n'
    sql << '           JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '           WHERE o.status <> \'cancelled\'\n'
    sql << '           GROUP BY 1, 2\n'
    sql << '          ) a ON a.m = t.month AND a.region = t.region\n'
    if (hasYear) {
        sql << 'WHERE year(t.month) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasRegion) {
        sql << '  AND t.region = ?\n'
        params << asDeclaredType('region', 'String', region)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd08-chart-monthly-revenue-vs-target', data)
}

// ─── Widget: gauge_pct_of_target_attainment (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_pct_of_target_attainment') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(a.actual) / sum(t.revenue_target), 4) AS pct_of_target\n'
    sql << 'FROM dash_demo.sales_targets t\n'
    sql << 'LEFT JOIN (SELECT date_trunc(\'month\', o.order_ts) AS m,\n'
    sql << '                  g.region AS region,\n'
    sql << '                  sum(o.total_amount) AS actual\n'
    sql << '           FROM dash_demo.orders o\n'
    sql << '           JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '           WHERE o.status <> \'cancelled\'\n'
    sql << '           GROUP BY 1, 2\n'
    sql << '          ) a ON a.m = t.month AND a.region = t.region\n'
    if (hasYear) {
        sql << 'WHERE year(t.month) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasRegion) {
        sql << '  AND t.region = ?\n'
        params << asDeclaredType('region', 'String', region)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_pct_of_target_attainment', data)
}

// ─── Widget: pivot_dd08-pivot-variance-by-region-month (type=pivot, dataSource=sql) ───
if (!componentId || componentId == 'pivot_dd08-pivot-variance-by-region-month') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT t.region AS region,\n'
    sql << '       strftime(t.month, \'%Y-%m\') AS month,\n'
    sql << '       round(100.0 * (coalesce(a.actual, 0) - t.revenue_target)\n'
    sql << '                   / t.revenue_target, 2) AS variance_pct\n'
    sql << 'FROM dash_demo.sales_targets t\n'
    sql << 'LEFT JOIN (SELECT date_trunc(\'month\', o.order_ts) AS m,\n'
    sql << '                  g.region AS region,\n'
    sql << '                  sum(o.total_amount) AS actual\n'
    sql << '           FROM dash_demo.orders o\n'
    sql << '           JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '           WHERE o.status <> \'cancelled\'\n'
    sql << '           GROUP BY 1, 2\n'
    sql << '          ) a ON a.m = t.month AND a.region = t.region\n'
    if (hasYear) {
        sql << 'WHERE year(t.month) = year(CAST(? AS DATE))\n'
        params << asDeclaredType('year', 'Date', year)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << 'ORDER BY 1, 2\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('pivot_dd08-pivot-variance-by-region-month', data)
}

