package com.flowkraft.cubes;

import static org.junit.jupiter.api.Assertions.fail;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import com.flowkraft.reporting.dsl.cube.CubeOptions;
import com.flowkraft.reporting.dsl.cube.CubeOptionsParser;
import com.sourcekraft.documentburster.common.db.northwind.NorthwindFixture;

/**
 * Runs the SQL that CubeSqlGenerator produces for the five SHIPPED sample cubes
 * against a real Northwind database.
 *
 * CubeSqlGeneratorTest already covers generation, but every assertion there is
 * on the SQL TEXT - contains("country"), contains("group by"). Text assertions
 * cannot see a query that is well-formed and still refuses to run, which is
 * exactly the class of defect this test exists for.
 *
 * EACH CUBE IS SWEPT ON THE ENGINE IT ACTUALLY SHIPS ON. The five samples do not
 * share one connection: northwind-sales, -customers, -hr and -inventory are wired
 * to rbt-sample-northwind-sqlite-4f2, and northwind-warehouse to
 * rbt-sample-northwind-duckdb-4f2. That split matters because measure and segment
 * sql are hand-written fragments passed to the database verbatim - jOOQ handles
 * identifier quoting, nothing rewrites function calls. A cube proven only on
 * DuckDB can therefore ship broken: EXTRACT(YEAR FROM ...) runs there and is a
 * syntax error on SQLite, which is where four of these five cubes run.
 *
 * So the engine is not hardcoded here. It is read from each cube's own cube.xml
 * connectionId, which means repointing a cube at another connection moves its
 * sweep with it, and introducing a connection this test does not know how to open
 * fails the build rather than silently skipping.
 *
 * The databases are NorthwindFixture: generated by the same code path the packager
 * uses, never one of the gitignored files in db/. DuckDB is opened read-only; the
 * SQLite sweep works on its own copy in a temp directory, so neither canonical
 * fixture can be written to.
 *
 * The sweep is every dimension x all measures, per cube - the smallest shape a
 * user can ask for in the UI and the one most likely to be tried first.
 */
class CubeSampleSqlExecutesTest {

	private static final String SAMPLES_CUBES_DIR = "../../asbl/src/main/external-resources/db-template/config/samples-cubes";

	private static final List<String> SAMPLE_CUBES = List.of("northwind-sales", "northwind-customers", "northwind-hr",
			"northwind-inventory", "northwind-warehouse");

	private static final Pattern CONNECTION_ID = Pattern.compile("<connectionId>\\s*([^<\\s]+)\\s*</connectionId>");

	@TempDir
	Path tempDir;

	@Test
	void everySampleCubeDimensionProducesRunnableSql() throws Exception {
		// Group the cubes by the engine their shipped connection names, so each
		// group is swept once against one connection.
		Map<String, List<String>> cubesByVendor = new LinkedHashMap<>();
		for (String cubeName : SAMPLE_CUBES) {
			cubesByVendor.computeIfAbsent(shippedVendorOf(cubeName), vendor -> new ArrayList<>()).add(cubeName);
		}

		Map<String, List<String>> failuresByCube = new LinkedHashMap<>();
		int executed = 0;

		for (Map.Entry<String, List<String>> group : cubesByVendor.entrySet()) {
			String vendor = group.getKey();

			try (Connection connection = openFixtureFor(vendor)) {
				for (String cubeName : group.getValue()) {
					CubeOptions cube = parseSampleCube(cubeName);

					List<String> measureNames = namesOf(cube.getMeasures());
					List<String> failures = new ArrayList<>();

					List<String> dimensionNames = namesOf(cube.getDimensions());
					List<String> segmentNames = namesOf(cube.getSegments());

					for (String dimensionName : dimensionNames) {
						String sql = CubeSqlGenerator.generateSql(cube, List.of(dimensionName), measureNames, vendor);
						executed++;
						String error = runAndReportError(connection, sql);
						if (error != null) {
							failures.add(dimensionName + " -> " + error + "\n" + sql);
						}
					}

					// Segments land in the WHERE clause and are hand-written SQL, exactly
					// like measures - so they carry the same portability risk, and nothing
					// else ever executes them. Each is swept against the cube's first
					// dimension, which is enough to make the engine parse and run the
					// segment's own expression.
					if (!dimensionNames.isEmpty()) {
						for (String segmentName : segmentNames) {
							String sql = CubeSqlGenerator.generateSql(cube, List.of(dimensionNames.get(0)),
									measureNames, List.of(segmentName), vendor);
							executed++;
							String error = runAndReportError(connection, sql);
							if (error != null) {
								failures.add("segment " + segmentName + " -> " + error + "\n" + sql);
							}
						}
					}

					int swept = dimensionNames.size() + segmentNames.size();
					System.out.println(cubeName + " [" + vendor + "]: " + (swept - failures.size()) + " ok, "
							+ failures.size() + " failed (" + dimensionNames.size() + " dimensions, "
							+ segmentNames.size() + " segments)");
					if (!failures.isEmpty()) {
						failuresByCube.put(cubeName + " [" + vendor + "]", failures);
					}
				}
			}
		}

		if (!failuresByCube.isEmpty()) {
			StringBuilder message = new StringBuilder(
					"Generated cube SQL failed to execute (" + executed + " queries swept):\n");
			failuresByCube.forEach((cubeName, failures) -> {
				message.append("\n=== ").append(cubeName).append(" ===\n");
				failures.forEach(failure -> message.append(failure).append("\n"));
			});
			fail(message.toString());
		}
	}

	/**
	 * The engine a sample cube ships on, read from its own cube.xml rather than
	 * listed here, so the two never drift apart.
	 */
	private String shippedVendorOf(String cubeName) throws Exception {
		File cubeXml = new File(SAMPLES_CUBES_DIR, cubeName + "/cube.xml");
		if (!cubeXml.exists()) {
			throw new IllegalStateException("Sample cube descriptor not found: " + cubeXml.getAbsolutePath());
		}

		Matcher matcher = CONNECTION_ID.matcher(Files.readString(cubeXml.toPath()));
		if (!matcher.find()) {
			throw new IllegalStateException("No <connectionId> in " + cubeXml.getAbsolutePath()
					+ ", so there is no way to know which engine this cube must be proven on.");
		}

		String connectionId = matcher.group(1);
		if (connectionId.contains("sqlite")) {
			return "sqlite";
		}
		if (connectionId.contains("duckdb")) {
			return "duckdb";
		}
		throw new IllegalStateException("Sample cube " + cubeName + " points at connection '" + connectionId
				+ "', whose engine this test cannot recognise. Teach it how to open that engine rather than "
				+ "letting the cube go unswept - proving a cube on the wrong engine is what this test exists "
				+ "to prevent.");
	}

	/** Opens the fixture for {@code vendor} without ever writing to a canonical file. */
	private Connection openFixtureFor(String vendor) throws Exception {
		switch (vendor) {
			case "duckdb":
				// DuckDB refuses read-only and read-write opens of one file in a JVM, so
				// the fixture hands out a read-only connection rather than a copy.
				return NorthwindFixture.readOnly();
			case "sqlite":
				Path sqliteCopy = NorthwindFixture.writableSqliteCopy(tempDir.resolve("northwind.db"));
				return DriverManager.getConnection(
						"jdbc:sqlite:" + sqliteCopy.toAbsolutePath().toString().replace("\\", "/"));
			default:
				throw new IllegalStateException("No fixture for engine '" + vendor + "'.");
		}
	}

	private CubeOptions parseSampleCube(String cubeName) throws Exception {
		File configFile = new File(SAMPLES_CUBES_DIR, cubeName + "/" + cubeName + "-cube-config.groovy");
		if (!configFile.exists()) {
			throw new IllegalStateException("Sample cube config not found: " + configFile.getAbsolutePath());
		}
		return CubeOptionsParser.parseGroovyCubeDslCode(Files.readString(configFile.toPath()));
	}

	private List<String> namesOf(List<Map<String, Object>> fields) {
		List<String> names = new ArrayList<>();
		if (fields != null) {
			for (Map<String, Object> field : fields) {
				Object name = field.get("name");
				if (name != null) {
					names.add(name.toString());
				}
			}
		}
		return names;
	}

	/** Returns null when the query runs, otherwise the database's complaint. */
	private String runAndReportError(Connection connection, String sql) {
		try (Statement statement = connection.createStatement(); ResultSet rs = statement.executeQuery(sql)) {
			while (rs.next()) {
				// Drain it - a lazy engine can defer the error until the first fetch.
			}
			return null;
		} catch (Exception e) {
			return e.getMessage() == null ? e.toString() : e.getMessage().replace('\n', ' ');
		}
	}
}
