// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def plan = userVars?.get('plan')?.toString()
def hasPlan = (plan != null && !plan.isEmpty())

// ─── Widget: trend_month_mrr (type=trend, dataSource=sql) ───
if (!componentId || componentId == 'trend_month_mrr') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH months AS (\n'
    sql << '  SELECT CAST(date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)) - to_months(CAST(g.i AS INTEGER)) AS DATE) AS month\n'
    sql << '  FROM generate_series(0, 11) AS g(i)\n'
    sql << '),\n'
    sql << 'month_end AS (\n'
    sql << '  SELECT month,\n'
    sql << '         CAST(least(month + to_months(1) - to_days(1), (SELECT a.as_of FROM dash_demo.as_of a)) AS DATE) AS read_at\n'
    sql << '  FROM months\n'
    sql << ')\n'
    sql << 'SELECT m.month AS month,\n'
    sql << '       round(sum(s.mrr), 2) AS mrr\n'
    sql << 'FROM month_end m\n'
    sql << 'JOIN dash_demo.subscriptions s\n'
    sql << '  ON s.start_date <= m.read_at\n'
    sql << ' AND (s.cancel_date IS NULL OR s.cancel_date > m.read_at)\n'
    sql << 'WHERE true\n'
    if (hasPlan && listHasValues(plan)) {
        addInList(sql, params, plan, 'AND s.plan IN') { asDeclaredType('plan', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY m.month\n'
    sql << 'ORDER BY m.month\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('trend_month_mrr', data)
}

// ─── Widget: number_active_subscribers_subscribers (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_active_subscribers_subscribers') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) AS active_subscribers\n'
    sql << 'FROM dash_demo.subscriptions s\n'
    sql << 'WHERE true\n'
    if (hasPlan && listHasValues(plan)) {
        addInList(sql, params, plan, 'AND s.plan IN') { asDeclaredType('plan', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  AND s.cancel_date IS NULL\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_active_subscribers_subscribers', data)
}

// ─── Widget: gauge_churn_last_month_month (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_churn_last_month_month') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(count(*) FILTER (WHERE date_trunc(\'month\', s.cancel_date) = date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)))\n'
    sql << '             / count(*)::DOUBLE, 4) AS churn_last_month\n'
    sql << 'FROM dash_demo.subscriptions s\n'
    sql << 'WHERE true\n'
    if (hasPlan && listHasValues(plan)) {
        addInList(sql, params, plan, 'AND s.plan IN') { asDeclaredType('plan', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  AND s.start_date < date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a))\n'
    sql << '  AND (s.cancel_date IS NULL OR s.cancel_date >= date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)))\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_churn_last_month_month', data)
}

// ─── Widget: chart_dd15-chart-waterfall-mrr-movement (type=chart, dataSource=script) ───
if (!componentId || componentId == 'chart_dd15-chart-waterfall-mrr-movement') {
    def chart_dd15_chart_waterfall_mrr_movement_data = { ->
        // What moved MRR over the last 12 months, in the order a reader follows: what came in, what grew,
        // what came back, what shrank, what left. The plan filter arrives as the comma-separated text of the
        // plans the viewer chose, so it is read into rows first - with nothing chosen there are no rows and
        // every plan counts.
        dbSql.rows("""WITH chosen AS (
          SELECT trim(p) AS plan
          FROM unnest(string_split(?, ',')) AS t(p)
          WHERE trim(p) <> ''
        )
        SELECT CASE ch.change_type
                 WHEN 'new' THEN 'New'
                 WHEN 'expansion' THEN 'Expansion'
                 WHEN 'reactivation' THEN 'Reactivation'
                 WHEN 'contraction' THEN 'Contraction'
                 ELSE 'Churn' END AS movement,
               round(sum(ch.mrr_delta), 2) AS mrr_delta
        FROM dash_demo.subscription_changes ch
        JOIN dash_demo.subscriptions s ON s.subscription_id = ch.subscription_id
        WHERE ch.change_date > (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 12 MONTH
          AND (NOT EXISTS (SELECT 1 FROM chosen) OR s.plan IN (SELECT plan FROM chosen))
        GROUP BY movement
        ORDER BY CASE movement
                   WHEN 'New' THEN 1
                   WHEN 'Expansion' THEN 2
                   WHEN 'Reactivation' THEN 3
                   WHEN 'Contraction' THEN 4
                   ELSE 5 END""", [plan])
    }()
    ctx.reportData('chart_dd15-chart-waterfall-mrr-movement', chart_dd15_chart_waterfall_mrr_movement_data)
}

// ─── Widget: chart_dd15-chart-churn-reasons (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd15-chart-churn-reasons') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT "cancel_reason", COUNT("subscription_id") AS "subscription_id_count"\n'
    sql << 'FROM "dash_demo"."subscriptions"\n'
    sql << 'WHERE "status" = \'cancelled\'\n'
    if (hasPlan && listHasValues(plan)) {
        addInList(sql, params, plan, 'AND "plan" IN') { asDeclaredType('plan', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY "cancel_reason"\n'
    sql << 'ORDER BY COUNT("subscription_id") DESC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd15-chart-churn-reasons', data)
}

// ─── Widget: chart_dd15-chart-mrr-by-plan (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd15-chart-mrr-by-plan') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH months AS (\n'
    sql << '  SELECT CAST(date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)) - to_months(CAST(g.i AS INTEGER)) AS DATE) AS month\n'
    sql << '  FROM generate_series(0, 11) AS g(i)\n'
    sql << '),\n'
    sql << 'month_end AS (\n'
    sql << '  SELECT month,\n'
    sql << '         CAST(least(month + to_months(1) - to_days(1), (SELECT a.as_of FROM dash_demo.as_of a)) AS DATE) AS read_at\n'
    sql << '  FROM months\n'
    sql << ')\n'
    sql << 'SELECT strftime(m.month, \'%Y-%m\') AS month,\n'
    sql << '       s.plan AS plan,\n'
    sql << '       round(sum(s.mrr), 2) AS mrr\n'
    sql << 'FROM month_end m\n'
    sql << 'JOIN dash_demo.subscriptions s\n'
    sql << '  ON s.start_date <= m.read_at\n'
    sql << ' AND (s.cancel_date IS NULL OR s.cancel_date > m.read_at)\n'
    sql << 'WHERE true\n'
    if (hasPlan && listHasValues(plan)) {
        addInList(sql, params, plan, 'AND s.plan IN') { asDeclaredType('plan', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY m.month, s.plan\n'
    sql << 'ORDER BY m.month, s.plan\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd15-chart-mrr-by-plan', data)
}

// ─── Widget: pivot_dd15-pivot-subscriber-cohorts (type=pivot, dataSource=sql) ───
if (!componentId || componentId == 'pivot_dd15-pivot-subscriber-cohorts') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH months AS (\n'
    sql << '  SELECT CAST(date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)) - to_months(CAST(g.i AS INTEGER)) AS DATE) AS month\n'
    sql << '  FROM generate_series(0, 11) AS g(i)\n'
    sql << ')\n'
    sql << 'SELECT year(s.start_date) || \' Q\' || quarter(s.start_date) AS cohort,\n'
    sql << '       strftime(m.month, \'%Y-%m\') AS month,\n'
    sql << '       round(100.0 * count(*) FILTER (WHERE s.cancel_date IS NULL\n'
    sql << '                                        OR s.cancel_date >= m.month + to_months(1))\n'
    sql << '             / count(*), 1) AS retained_pct\n'
    sql << 'FROM months m\n'
    sql << 'JOIN dash_demo.subscriptions s\n'
    sql << '  ON s.start_date < m.month\n'
    sql << ' AND (s.cancel_date IS NULL OR s.cancel_date >= m.month)\n'
    sql << 'WHERE true\n'
    if (hasPlan && listHasValues(plan)) {
        addInList(sql, params, plan, 'AND s.plan IN') { asDeclaredType('plan', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  AND s.start_date >= DATE \'2025-01-01\'\n'
    sql << 'GROUP BY cohort, m.month\n'
    sql << 'ORDER BY cohort, m.month\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('pivot_dd15-pivot-subscriber-cohorts', data)
}

