// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def period = userVars?.get('period')?.toString()
def hasPeriod = (period != null && !period.isEmpty())
def department = userVars?.get('department')?.toString()
def hasDepartment = (department != null && !department.isEmpty())

// ─── Widget: number_payroll_cost_cost (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_payroll_cost_cost') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(pl.gross_pay + pl.employer_taxes + pl.benefits), 2) AS payroll_cost\n'
    sql << 'FROM dash_demo.payroll_lines pl\n'
    sql << 'JOIN dash_demo.employees e ON e.employee_id = pl.employee_id\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'WHERE true\n'
    if (hasPeriod) {
        sql << '  AND strftime(pl.period_month, \'%Y-%m\') = ?\n'
        params << asDeclaredType('period', 'String', period)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDepartment && listHasValues(department)) {
        addInList(sql, params, department, 'AND d.name IN') { asDeclaredType('department', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_payroll_cost_cost', data)
}

// ─── Widget: number_average_gross_pay_pay (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_average_gross_pay_pay') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(avg(pl.gross_pay), 2) AS average_gross_pay\n'
    sql << 'FROM dash_demo.payroll_lines pl\n'
    sql << 'JOIN dash_demo.employees e ON e.employee_id = pl.employee_id\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'WHERE true\n'
    if (hasPeriod) {
        sql << '  AND strftime(pl.period_month, \'%Y-%m\') = ?\n'
        params << asDeclaredType('period', 'String', period)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDepartment && listHasValues(department)) {
        addInList(sql, params, department, 'AND d.name IN') { asDeclaredType('department', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_average_gross_pay_pay', data)
}

// ─── Widget: number_overtime_hours_hours (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_overtime_hours_hours') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(pl.overtime_hours), 2) AS overtime_hours\n'
    sql << 'FROM dash_demo.payroll_lines pl\n'
    sql << 'JOIN dash_demo.employees e ON e.employee_id = pl.employee_id\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'WHERE true\n'
    if (hasPeriod) {
        sql << '  AND strftime(pl.period_month, \'%Y-%m\') = ?\n'
        params << asDeclaredType('period', 'String', period)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDepartment && listHasValues(department)) {
        addInList(sql, params, department, 'AND d.name IN') { asDeclaredType('department', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_overtime_hours_hours', data)
}

// ─── Widget: chart_dd17-chart-cost-per-month-by-department (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd17-chart-cost-per-month-by-department') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT strftime(pl.period_month, \'%Y-%m\') AS month,\n'
    sql << '       d.name AS department,\n'
    sql << '       round(sum(pl.gross_pay + pl.employer_taxes + pl.benefits), 2) AS total_cost\n'
    sql << 'FROM dash_demo.payroll_lines pl\n'
    sql << 'JOIN dash_demo.employees e ON e.employee_id = pl.employee_id\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'WHERE true\n'
    if (hasDepartment && listHasValues(department)) {
        addInList(sql, params, department, 'AND d.name IN') { asDeclaredType('department', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY month, department\n'
    sql << 'ORDER BY month, department\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd17-chart-cost-per-month-by-department', data)
}

// ─── Widget: chart_dd17-chart-cost-components (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd17-chart-cost-components') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH scope AS (\n'
    sql << '  SELECT pl.base_pay AS base_pay,\n'
    sql << '         pl.bonus AS bonus,\n'
    sql << '         pl.overtime_pay AS overtime_pay,\n'
    sql << '         pl.employer_taxes AS employer_taxes,\n'
    sql << '         pl.benefits AS benefits\n'
    sql << '  FROM dash_demo.payroll_lines pl\n'
    sql << '  JOIN dash_demo.employees e ON e.employee_id = pl.employee_id\n'
    sql << '  JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << '  WHERE true\n'
    if (hasPeriod) {
        sql << '    AND strftime(pl.period_month, \'%Y-%m\') = ?\n'
        params << asDeclaredType('period', 'String', period)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasDepartment && listHasValues(department)) {
        addInList(sql, params, department, 'AND d.name IN') { asDeclaredType('department', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '),\n'
    sql << 'totals AS (\n'
    sql << '  SELECT round(sum(base_pay), 2) AS base_pay,\n'
    sql << '         round(sum(bonus), 2) AS bonus,\n'
    sql << '         round(sum(overtime_pay), 2) AS overtime_pay,\n'
    sql << '         round(sum(employer_taxes), 2) AS employer_taxes,\n'
    sql << '         round(sum(benefits), 2) AS benefits\n'
    sql << '  FROM scope\n'
    sql << ')\n'
    sql << 'SELECT component, amount\n'
    sql << 'FROM (SELECT 1 AS ord, \'Base pay\' AS component, base_pay AS amount FROM totals\n'
    sql << '      UNION ALL SELECT 2, \'Bonus\', bonus FROM totals\n'
    sql << '      UNION ALL SELECT 3, \'Overtime\', overtime_pay FROM totals\n'
    sql << '      UNION ALL SELECT 4, \'Employer taxes\', employer_taxes FROM totals\n'
    sql << '      UNION ALL SELECT 5, \'Benefits\', benefits FROM totals)\n'
    sql << 'ORDER BY ord\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd17-chart-cost-components', data)
}

// ─── Widget: chart_dd17-chart-warehouse-overtime-hours (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd17-chart-warehouse-overtime-hours') {
    def sql = new StringBuilder()
    sql << 'SELECT strftime(pl.period_month, \'%Y-%m\') AS month,\n'
    sql << '       round(sum(pl.overtime_hours), 1) AS overtime_hours\n'
    sql << 'FROM dash_demo.payroll_lines pl\n'
    sql << 'JOIN dash_demo.employees e ON e.employee_id = pl.employee_id\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'WHERE d.name = \'Warehouse\'\n'
    sql << 'GROUP BY month\n'
    sql << 'ORDER BY month\n'
    def data = dbSql.rows(sql.toString())
    ctx.reportData('chart_dd17-chart-warehouse-overtime-hours', data)
}

// ─── Widget: tabulator_dd17-table-cost-change-by-department (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd17-table-cost-change-by-department') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH lines AS (\n'
    sql << '  SELECT d.name AS department,\n'
    sql << '         date_trunc(\'month\', pl.period_month) AS month,\n'
    sql << '         pl.gross_pay + pl.employer_taxes + pl.benefits AS cost\n'
    sql << '  FROM dash_demo.payroll_lines pl\n'
    sql << '  JOIN dash_demo.employees e ON e.employee_id = pl.employee_id\n'
    sql << '  JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << '  WHERE true\n'
    if (hasPeriod) {
        sql << '    AND date_trunc(\'month\', pl.period_month) IN (CAST(? || \'-01\' AS DATE), CAST(? || \'-01\' AS DATE) - INTERVAL 12 MONTH)\n'
        params << asDeclaredType('period', 'String', period)
        params << asDeclaredType('period', 'String', period)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasDepartment && listHasValues(department)) {
        addInList(sql, params, department, 'AND d.name IN') { asDeclaredType('department', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '),\n'
    sql << 'per_month AS (\n'
    sql << '  SELECT department, month, sum(cost) AS cost, count(*) AS people\n'
    sql << '  FROM lines\n'
    sql << '  GROUP BY department, month\n'
    sql << '),\n'
    sql << 'paired AS (\n'
    sql << '  SELECT n.department AS department,\n'
    sql << '         n.people AS people_now,\n'
    sql << '         p.people AS people_last_year,\n'
    sql << '         n.cost AS cost_now,\n'
    sql << '         p.cost AS cost_last_year\n'
    sql << '  FROM per_month n\n'
    sql << '  JOIN per_month p\n'
    sql << '    ON p.department = n.department\n'
    sql << '   AND p.month = n.month - INTERVAL 12 MONTH\n'
    sql << ')\n'
    sql << 'SELECT department,\n'
    sql << '       people_now - people_last_year AS people_change,\n'
    sql << '       round(cost_now - cost_last_year, 2) AS cost_change,\n'
    sql << '       round((people_now - people_last_year) * (cost_last_year / people_last_year), 2) AS from_more_people,\n'
    sql << '       round((cost_now / people_now - cost_last_year / people_last_year) * people_now, 2) AS from_higher_pay\n'
    sql << 'FROM paired\n'
    sql << 'ORDER BY cost_change DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd17-table-cost-change-by-department', data)
}

