// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def department = userVars?.get('department')?.toString()
def hasDepartment = (department != null && !department.isEmpty())
def country = userVars?.get('country')?.toString()
def hasCountry = (country != null && !country.isEmpty())

// ─── Widget: number_headcount_headcount (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_headcount_headcount') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) AS headcount\n'
    sql << 'FROM dash_demo.employees e\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = e.city_id\n'
    sql << 'WHERE true\n'
    if (hasDepartment) {
        sql << '  AND d.name = ?\n'
        params << asDeclaredType('department', 'String', department)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND e.hire_date <= (SELECT a.as_of FROM dash_demo.as_of a)\n'
    sql << '  AND (e.termination_date IS NULL OR e.termination_date > (SELECT a.as_of FROM dash_demo.as_of a))\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_headcount_headcount', data)
}

// ─── Widget: number_hires_ytd_ytd (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_hires_ytd_ytd') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) AS hires_ytd\n'
    sql << 'FROM dash_demo.employees e\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = e.city_id\n'
    sql << 'WHERE true\n'
    if (hasDepartment) {
        sql << '  AND d.name = ?\n'
        params << asDeclaredType('department', 'String', department)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND e.hire_date >= CAST(date_trunc(\'year\', (SELECT a.as_of FROM dash_demo.as_of a)) AS DATE)\n'
    sql << '  AND e.hire_date <= (SELECT a.as_of FROM dash_demo.as_of a)\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_hires_ytd_ytd', data)
}

// ─── Widget: number_leavers_ytd_ytd (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_leavers_ytd_ytd') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) AS leavers_ytd\n'
    sql << 'FROM dash_demo.employees e\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = e.city_id\n'
    sql << 'WHERE true\n'
    if (hasDepartment) {
        sql << '  AND d.name = ?\n'
        params << asDeclaredType('department', 'String', department)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND e.termination_date >= CAST(date_trunc(\'year\', (SELECT a.as_of FROM dash_demo.as_of a)) AS DATE)\n'
    sql << '  AND e.termination_date <= (SELECT a.as_of FROM dash_demo.as_of a)\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_leavers_ytd_ytd', data)
}

// ─── Widget: chart_dd18-chart-headcount-over-time (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd18-chart-headcount-over-time') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH months AS (\n'
    sql << '  SELECT CAST(date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)) - to_months(CAST(x.i AS INTEGER)) AS DATE) AS month\n'
    sql << '  FROM generate_series(0, 32) AS x(i)\n'
    sql << ')\n'
    sql << 'SELECT strftime(m.month, \'%Y-%m\') AS month,\n'
    sql << '       count(*) AS headcount\n'
    sql << 'FROM months m\n'
    sql << 'JOIN dash_demo.employees e\n'
    sql << '  ON e.hire_date <= m.month + to_months(1) - to_days(1)\n'
    sql << ' AND (e.termination_date IS NULL OR e.termination_date > m.month + to_months(1) - to_days(1))\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = e.city_id\n'
    sql << 'WHERE true\n'
    if (hasDepartment) {
        sql << '  AND d.name = ?\n'
        params << asDeclaredType('department', 'String', department)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY m.month\n'
    sql << 'ORDER BY m.month\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd18-chart-headcount-over-time', data)
}

// ─── Widget: chart_dd18-chart-attrition-by-department (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd18-chart-attrition-by-department') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH scope AS (\n'
    sql << '  SELECT e.department_id AS department_id,\n'
    sql << '         d.name AS department,\n'
    sql << '         e.hire_date AS hire_date,\n'
    sql << '         e.termination_date AS termination_date\n'
    sql << '  FROM dash_demo.employees e\n'
    sql << '  JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << '  JOIN dash_demo.geo_cities g ON g.city_id = e.city_id\n'
    sql << '  WHERE true\n'
    if (hasDepartment) {
        sql << '    AND d.name = ?\n'
        params << asDeclaredType('department', 'String', department)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '    AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    sql << '),\n'
    sql << 'grouped AS (\n'
    sql << '  SELECT CASE WHEN (SELECT count(*) FROM dash_demo.employees e2\n'
    sql << '                    WHERE e2.department_id = s.department_id\n'
    sql << '                      AND e2.termination_date IS NOT NULL) >= 8\n'
    sql << '              THEN s.department ELSE \'Other departments\' END AS department,\n'
    sql << '         s.hire_date AS hire_date,\n'
    sql << '         s.termination_date AS termination_date\n'
    sql << '  FROM scope s\n'
    sql << '),\n'
    sql << 'months AS (\n'
    sql << '  SELECT CAST(date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)) - to_months(CAST(x.i AS INTEGER)) AS DATE) AS month\n'
    sql << '  FROM generate_series(0, 32) AS x(i)\n'
    sql << '),\n'
    sql << 'heads AS (\n'
    sql << '  SELECT gr.department AS department, m.month AS month, count(*) AS heads\n'
    sql << '  FROM months m\n'
    sql << '  JOIN grouped gr\n'
    sql << '    ON gr.hire_date <= m.month + to_months(1) - to_days(1)\n'
    sql << '   AND (gr.termination_date IS NULL OR gr.termination_date > m.month + to_months(1) - to_days(1))\n'
    sql << '  GROUP BY gr.department, m.month\n'
    sql << '),\n'
    sql << 'average_heads AS (\n'
    sql << '  SELECT department, avg(heads) AS avg_heads FROM heads GROUP BY department\n'
    sql << '),\n'
    sql << 'leavers AS (\n'
    sql << '  SELECT department, count(*) AS leavers\n'
    sql << '  FROM grouped\n'
    sql << '  WHERE termination_date >= CAST(date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)) - to_months(32) AS DATE)\n'
    sql << '    AND termination_date <= (SELECT a.as_of FROM dash_demo.as_of a)\n'
    sql << '  GROUP BY department\n'
    sql << ')\n'
    sql << 'SELECT a.department || \' (\' || coalesce(l.leavers, 0) || \')\' AS department,\n'
    sql << '       round(100.0 * coalesce(l.leavers, 0) / a.avg_heads * 12.0 / 33.0, 2) AS attrition_pct\n'
    sql << 'FROM average_heads a\n'
    sql << 'LEFT JOIN leavers l ON l.department = a.department\n'
    sql << 'ORDER BY attrition_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd18-chart-attrition-by-department', data)
}

// ─── Widget: chart_dd18-chart-boxplot-salary-by-level (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd18-chart-boxplot-salary-by-level') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT e.level || \' - \' || CASE WHEN d.name = \'Customer Support\'\n'
    sql << '                                THEN \'Customer Support\' ELSE \'Everyone else\' END AS level_and_side,\n'
    sql << '       e.base_salary_annual AS base_salary_annual\n'
    sql << 'FROM dash_demo.employees e\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = e.city_id\n'
    sql << 'WHERE true\n'
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND e.hire_date <= (SELECT a.as_of FROM dash_demo.as_of a)\n'
    sql << '  AND (e.termination_date IS NULL OR e.termination_date > (SELECT a.as_of FROM dash_demo.as_of a))\n'
    sql << '  AND e.level IN (\'L1\', \'L2\', \'L3\')\n'
    sql << 'ORDER BY level_and_side, base_salary_annual\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd18-chart-boxplot-salary-by-level', data)
}

// ─── Widget: chart_dd18-chart-tenure-bins (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd18-chart-tenure-bins') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT CASE WHEN (SELECT a.as_of FROM dash_demo.as_of a) - e.hire_date < 365 THEN \'0-1 years\'\n'
    sql << '            WHEN (SELECT a.as_of FROM dash_demo.as_of a) - e.hire_date < 730 THEN \'1-2 years\'\n'
    sql << '            WHEN (SELECT a.as_of FROM dash_demo.as_of a) - e.hire_date < 1095 THEN \'2-3 years\'\n'
    sql << '            WHEN (SELECT a.as_of FROM dash_demo.as_of a) - e.hire_date < 1825 THEN \'3-5 years\'\n'
    sql << '            WHEN (SELECT a.as_of FROM dash_demo.as_of a) - e.hire_date < 3650 THEN \'5-10 years\'\n'
    sql << '            ELSE \'10+ years\' END AS tenure,\n'
    sql << '       count(*) AS people\n'
    sql << 'FROM dash_demo.employees e\n'
    sql << 'JOIN dash_demo.departments d ON d.department_id = e.department_id\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = e.city_id\n'
    sql << 'WHERE true\n'
    if (hasDepartment) {
        sql << '  AND d.name = ?\n'
        params << asDeclaredType('department', 'String', department)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '  AND e.hire_date <= (SELECT a.as_of FROM dash_demo.as_of a)\n'
    sql << '  AND (e.termination_date IS NULL OR e.termination_date > (SELECT a.as_of FROM dash_demo.as_of a))\n'
    sql << 'GROUP BY tenure\n'
    sql << 'ORDER BY min((SELECT a.as_of FROM dash_demo.as_of a) - e.hire_date)\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd18-chart-tenure-bins', data)
}

