// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def region = userVars?.get('region')?.toString()
def hasRegion = (region != null && !region.isEmpty())
def countries = userVars?.get('countries')?.toString()
def hasCountries = (countries != null && !countries.isEmpty())

// ─── Widget: map_dd03-map-revenue-by-country (type=map, dataSource=sql) ───
if (!componentId || componentId == 'map_dd03-map-revenue-by-country') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT g.country AS country,\n'
    sql << '       round(sum(o.total_amount), 2) AS revenue\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasRegion) {
        sql << '  AND g.region = ?\n'
        params << asDeclaredType('region', 'String', region)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountries && listHasValues(countries)) {
        addInList(sql, params, countries, 'AND g.country IN') { asDeclaredType('countries', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY revenue DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('map_dd03-map-revenue-by-country', data)
}

// ─── Widget: chart_dd03-chart-average-order-value-by-country (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd03-chart-average-order-value-by-country') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT g.country AS country,\n'
    sql << '       round(avg(o.total_amount), 2) AS average_order_value\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasRegion) {
        sql << '  AND g.region = ?\n'
        params << asDeclaredType('region', 'String', region)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountries && listHasValues(countries)) {
        addInList(sql, params, countries, 'AND g.country IN') { asDeclaredType('countries', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY average_order_value DESC\n'
    sql << 'LIMIT 10\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd03-chart-average-order-value-by-country', data)
}

// ─── Widget: map_dd03-map-orders-by-city (type=map, dataSource=sql) ───
if (!componentId || componentId == 'map_dd03-map-orders-by-city') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT g.city AS city,\n'
    sql << '       g.country AS country,\n'
    sql << '       g.latitude AS latitude,\n'
    sql << '       g.longitude AS longitude,\n'
    sql << '       count(*) AS orders\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasRegion) {
        sql << '  AND g.region = ?\n'
        params << asDeclaredType('region', 'String', region)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountries && listHasValues(countries)) {
        addInList(sql, params, countries, 'AND g.country IN') { asDeclaredType('countries', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY 1, 2, 3, 4\n'
    sql << 'ORDER BY orders DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('map_dd03-map-orders-by-city', data)
}

// ─── Widget: tabulator_dd03-table-country-growth (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd03-table-country-growth') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT bucket AS country,\n'
    sql << '       round(revenue_this_year, 2) AS revenue_this_year,\n'
    sql << '       round(revenue_same_period_last_year, 2) AS revenue_same_period_last_year,\n'
    sql << '       round(100.0 * (revenue_this_year / nullif(revenue_same_period_last_year, 0) - 1), 2) AS growth_pct\n'
    sql << 'FROM (SELECT CASE WHEN c.orders_this_year >= 150 THEN c.country ELSE \'Other countries\' END AS bucket,\n'
    sql << '             sum(c.revenue_this_year) AS revenue_this_year,\n'
    sql << '             sum(c.revenue_same_period_last_year) AS revenue_same_period_last_year\n'
    sql << '      FROM (SELECT g.country AS country,\n'
    sql << '                   count(CASE WHEN o.order_ts >= date_trunc(\'year\', (SELECT a.as_of FROM dash_demo.as_of a)) THEN 1 END) AS orders_this_year,\n'
    sql << '                   sum(CASE WHEN o.order_ts >= date_trunc(\'year\', (SELECT a.as_of FROM dash_demo.as_of a)) THEN o.total_amount ELSE 0 END) AS revenue_this_year,\n'
    sql << '                   sum(CASE WHEN o.order_ts >= date_trunc(\'year\', (SELECT a.as_of FROM dash_demo.as_of a)) - INTERVAL 1 YEAR AND o.order_ts < (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 1 YEAR + INTERVAL 1 DAY THEN o.total_amount ELSE 0 END) AS revenue_same_period_last_year\n'
    sql << '            FROM dash_demo.orders o\n'
    sql << '            JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '            WHERE o.status <> \'cancelled\'\n'
    if (hasRegion) {
        sql << '              AND g.region = ?\n'
        params << asDeclaredType('region', 'String', region)
    } else {
        sql << '              AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountries && listHasValues(countries)) {
        addInList(sql, params, countries, 'AND g.country IN') { asDeclaredType('countries', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '            GROUP BY 1) c\n'
    sql << '      GROUP BY 1) f\n'
    sql << 'ORDER BY CASE WHEN bucket = \'Other countries\' THEN 1 ELSE 0 END, growth_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd03-table-country-growth', data)
}

