// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def metric = userVars?.get('metric')?.toString()
def hasMetric = (metric != null && !metric.isEmpty())

// ─── Widget: trend_month_month (type=trend, dataSource=script) ───
if (!componentId || componentId == 'trend_month_month') {
    def trend_month_month_data = { ->
        // The radio's five words are the whole whitelist: the chosen one goes to the database as a value,
        // never as SQL text, so nothing a filter can carry reaches the query itself.
        if (!['Revenue', 'Orders', 'New customers', 'Tickets', 'Payroll cost'].contains(metric)) return []
        return dbSql.rows("""WITH line_totals AS (
          SELECT l.order_id AS order_id, sum(l.line_amount) AS line_total
          FROM dash_demo.order_lines l
          GROUP BY l.order_id
        ),
        feed AS (
          -- Revenue at line grain: each order's own total spread over its lines in proportion to what they
          -- cost, so the categories below add up to the number above them.
          SELECT 'Revenue' AS metric,
                 o.order_ts AS happened_at,
                 o.total_amount * l.line_amount / t.line_total AS value,
                 p.category AS made_of,
                 g.country AS country
          FROM dash_demo.order_lines l
          JOIN line_totals t ON t.order_id = l.order_id
          JOIN dash_demo.orders o ON o.order_id = l.order_id
          JOIN dash_demo.products p ON p.product_id = l.product_id
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'Orders', o.order_ts, 1, o.channel, g.country
          FROM dash_demo.orders o
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'New customers', c.signup_date, 1, c.acquisition_channel, g.country
          FROM dash_demo.customers c
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Tickets', tk.opened_ts, 1, tk.category, g.country
          FROM dash_demo.support_tickets tk
          JOIN dash_demo.customers c ON c.customer_id = tk.customer_id
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Payroll cost', pl.period_month,
                 pl.gross_pay + pl.employer_taxes + pl.benefits, d.name, g.country
          FROM dash_demo.payroll_lines pl
          JOIN dash_demo.employees e ON e.employee_id = pl.employee_id
          JOIN dash_demo.departments d ON d.department_id = e.department_id
          JOIN dash_demo.geo_cities g ON g.city_id = e.city_id
        )
        SELECT date_trunc('month', f.happened_at)::DATE AS month,
               round(sum(f.value), 2) AS value
        FROM feed f
        WHERE f.metric = ?
        GROUP BY month
        ORDER BY month""", [metric])
    }()
    ctx.reportData('trend_month_month', trend_month_month_data)
}

// ─── Widget: number_metric_ytd_ytd (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_metric_ytd_ytd') {
    def number_metric_ytd_ytd_data = { ->
        // The radio's five words are the whole whitelist: the chosen one goes to the database as a value,
        // never as SQL text, so nothing a filter can carry reaches the query itself.
        if (!['Revenue', 'Orders', 'New customers', 'Tickets', 'Payroll cost'].contains(metric)) return []
        return dbSql.rows("""WITH line_totals AS (
          SELECT l.order_id AS order_id, sum(l.line_amount) AS line_total
          FROM dash_demo.order_lines l
          GROUP BY l.order_id
        ),
        feed AS (
          -- Revenue at line grain: each order's own total spread over its lines in proportion to what they
          -- cost, so the categories below add up to the number above them.
          SELECT 'Revenue' AS metric,
                 o.order_ts AS happened_at,
                 o.total_amount * l.line_amount / t.line_total AS value,
                 p.category AS made_of,
                 g.country AS country
          FROM dash_demo.order_lines l
          JOIN line_totals t ON t.order_id = l.order_id
          JOIN dash_demo.orders o ON o.order_id = l.order_id
          JOIN dash_demo.products p ON p.product_id = l.product_id
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'Orders', o.order_ts, 1, o.channel, g.country
          FROM dash_demo.orders o
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'New customers', c.signup_date, 1, c.acquisition_channel, g.country
          FROM dash_demo.customers c
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Tickets', tk.opened_ts, 1, tk.category, g.country
          FROM dash_demo.support_tickets tk
          JOIN dash_demo.customers c ON c.customer_id = tk.customer_id
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Payroll cost', pl.period_month,
                 pl.gross_pay + pl.employer_taxes + pl.benefits, d.name, g.country
          FROM dash_demo.payroll_lines pl
          JOIN dash_demo.employees e ON e.employee_id = pl.employee_id
          JOIN dash_demo.departments d ON d.department_id = e.department_id
          JOIN dash_demo.geo_cities g ON g.city_id = e.city_id
        )
        SELECT round(sum(f.value), 2) AS metric_ytd
        FROM feed f
        WHERE f.metric = ?
          AND f.happened_at >= date_trunc('year', (SELECT a.as_of FROM dash_demo.as_of a))
          AND f.happened_at <= (SELECT a.as_of FROM dash_demo.as_of a)""", [metric])
    }()
    ctx.reportData('number_metric_ytd_ytd', number_metric_ytd_ytd_data)
}

// ─── Widget: number_vs_last_year_year (type=number, dataSource=script) ───
if (!componentId || componentId == 'number_vs_last_year_year') {
    def number_vs_last_year_year_data = { ->
        // The radio's five words are the whole whitelist: the chosen one goes to the database as a value,
        // never as SQL text, so nothing a filter can carry reaches the query itself.
        if (!['Revenue', 'Orders', 'New customers', 'Tickets', 'Payroll cost'].contains(metric)) return []
        return dbSql.rows("""WITH line_totals AS (
          SELECT l.order_id AS order_id, sum(l.line_amount) AS line_total
          FROM dash_demo.order_lines l
          GROUP BY l.order_id
        ),
        feed AS (
          -- Revenue at line grain: each order's own total spread over its lines in proportion to what they
          -- cost, so the categories below add up to the number above them.
          SELECT 'Revenue' AS metric,
                 o.order_ts AS happened_at,
                 o.total_amount * l.line_amount / t.line_total AS value,
                 p.category AS made_of,
                 g.country AS country
          FROM dash_demo.order_lines l
          JOIN line_totals t ON t.order_id = l.order_id
          JOIN dash_demo.orders o ON o.order_id = l.order_id
          JOIN dash_demo.products p ON p.product_id = l.product_id
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'Orders', o.order_ts, 1, o.channel, g.country
          FROM dash_demo.orders o
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'New customers', c.signup_date, 1, c.acquisition_channel, g.country
          FROM dash_demo.customers c
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Tickets', tk.opened_ts, 1, tk.category, g.country
          FROM dash_demo.support_tickets tk
          JOIN dash_demo.customers c ON c.customer_id = tk.customer_id
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Payroll cost', pl.period_month,
                 pl.gross_pay + pl.employer_taxes + pl.benefits, d.name, g.country
          FROM dash_demo.payroll_lines pl
          JOIN dash_demo.employees e ON e.employee_id = pl.employee_id
          JOIN dash_demo.departments d ON d.department_id = e.department_id
          JOIN dash_demo.geo_cities g ON g.city_id = e.city_id
        )
        SELECT round(
                 sum(CASE WHEN f.happened_at >= date_trunc('year', (SELECT a.as_of FROM dash_demo.as_of a))
                          THEN f.value END)
                 / sum(CASE WHEN f.happened_at < date_trunc('year', (SELECT a.as_of FROM dash_demo.as_of a))
                            THEN f.value END) - 1, 4) AS vs_last_year
        FROM feed f
        WHERE f.metric = ?
          AND ((f.happened_at >= date_trunc('year', (SELECT a.as_of FROM dash_demo.as_of a))
          AND f.happened_at <= (SELECT a.as_of FROM dash_demo.as_of a))
            OR (f.happened_at >= date_trunc('year', (SELECT a.as_of FROM dash_demo.as_of a)) - INTERVAL 1 YEAR
              AND f.happened_at <= (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 1 YEAR))""", [metric])
    }()
    ctx.reportData('number_vs_last_year_year', number_vs_last_year_year_data)
}

// ─── Widget: chart_dd24-chart-metric-over-time (type=chart, dataSource=script) ───
if (!componentId || componentId == 'chart_dd24-chart-metric-over-time') {
    def chart_dd24_chart_metric_over_time_data = { ->
        // The radio's five words are the whole whitelist: the chosen one goes to the database as a value,
        // never as SQL text, so nothing a filter can carry reaches the query itself.
        if (!['Revenue', 'Orders', 'New customers', 'Tickets', 'Payroll cost'].contains(metric)) return []
        return dbSql.rows("""WITH line_totals AS (
          SELECT l.order_id AS order_id, sum(l.line_amount) AS line_total
          FROM dash_demo.order_lines l
          GROUP BY l.order_id
        ),
        feed AS (
          -- Revenue at line grain: each order's own total spread over its lines in proportion to what they
          -- cost, so the categories below add up to the number above them.
          SELECT 'Revenue' AS metric,
                 o.order_ts AS happened_at,
                 o.total_amount * l.line_amount / t.line_total AS value,
                 p.category AS made_of,
                 g.country AS country
          FROM dash_demo.order_lines l
          JOIN line_totals t ON t.order_id = l.order_id
          JOIN dash_demo.orders o ON o.order_id = l.order_id
          JOIN dash_demo.products p ON p.product_id = l.product_id
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'Orders', o.order_ts, 1, o.channel, g.country
          FROM dash_demo.orders o
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'New customers', c.signup_date, 1, c.acquisition_channel, g.country
          FROM dash_demo.customers c
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Tickets', tk.opened_ts, 1, tk.category, g.country
          FROM dash_demo.support_tickets tk
          JOIN dash_demo.customers c ON c.customer_id = tk.customer_id
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Payroll cost', pl.period_month,
                 pl.gross_pay + pl.employer_taxes + pl.benefits, d.name, g.country
          FROM dash_demo.payroll_lines pl
          JOIN dash_demo.employees e ON e.employee_id = pl.employee_id
          JOIN dash_demo.departments d ON d.department_id = e.department_id
          JOIN dash_demo.geo_cities g ON g.city_id = e.city_id
        )
        SELECT date_trunc('month', f.happened_at)::DATE AS month,
               round(sum(f.value), 2) AS value
        FROM feed f
        WHERE f.metric = ?
        GROUP BY month
        ORDER BY month""", [metric])
    }()
    ctx.reportData('chart_dd24-chart-metric-over-time', chart_dd24_chart_metric_over_time_data)
}

// ─── Widget: chart_dd24-chart-what-it-is-made-of (type=chart, dataSource=script) ───
if (!componentId || componentId == 'chart_dd24-chart-what-it-is-made-of') {
    def chart_dd24_chart_what_it_is_made_of_data = { ->
        // The radio's five words are the whole whitelist: the chosen one goes to the database as a value,
        // never as SQL text, so nothing a filter can carry reaches the query itself.
        if (!['Revenue', 'Orders', 'New customers', 'Tickets', 'Payroll cost'].contains(metric)) return []
        return dbSql.rows("""WITH line_totals AS (
          SELECT l.order_id AS order_id, sum(l.line_amount) AS line_total
          FROM dash_demo.order_lines l
          GROUP BY l.order_id
        ),
        feed AS (
          -- Revenue at line grain: each order's own total spread over its lines in proportion to what they
          -- cost, so the categories below add up to the number above them.
          SELECT 'Revenue' AS metric,
                 o.order_ts AS happened_at,
                 o.total_amount * l.line_amount / t.line_total AS value,
                 p.category AS made_of,
                 g.country AS country
          FROM dash_demo.order_lines l
          JOIN line_totals t ON t.order_id = l.order_id
          JOIN dash_demo.orders o ON o.order_id = l.order_id
          JOIN dash_demo.products p ON p.product_id = l.product_id
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'Orders', o.order_ts, 1, o.channel, g.country
          FROM dash_demo.orders o
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'New customers', c.signup_date, 1, c.acquisition_channel, g.country
          FROM dash_demo.customers c
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Tickets', tk.opened_ts, 1, tk.category, g.country
          FROM dash_demo.support_tickets tk
          JOIN dash_demo.customers c ON c.customer_id = tk.customer_id
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Payroll cost', pl.period_month,
                 pl.gross_pay + pl.employer_taxes + pl.benefits, d.name, g.country
          FROM dash_demo.payroll_lines pl
          JOIN dash_demo.employees e ON e.employee_id = pl.employee_id
          JOIN dash_demo.departments d ON d.department_id = e.department_id
          JOIN dash_demo.geo_cities g ON g.city_id = e.city_id
        )
        SELECT f.made_of AS made_of,
               round(sum(f.value), 2) AS value
        FROM feed f
        WHERE f.metric = ?
          AND f.happened_at >= date_trunc('year', (SELECT a.as_of FROM dash_demo.as_of a))
          AND f.happened_at <= (SELECT a.as_of FROM dash_demo.as_of a)
        GROUP BY f.made_of
        ORDER BY value DESC""", [metric])
    }()
    ctx.reportData('chart_dd24-chart-what-it-is-made-of', chart_dd24_chart_what_it_is_made_of_data)
}

// ─── Widget: chart_dd24-chart-by-month-of-year (type=chart, dataSource=script) ───
if (!componentId || componentId == 'chart_dd24-chart-by-month-of-year') {
    def chart_dd24_chart_by_month_of_year_data = { ->
        // The radio's five words are the whole whitelist: the chosen one goes to the database as a value,
        // never as SQL text, so nothing a filter can carry reaches the query itself.
        if (!['Revenue', 'Orders', 'New customers', 'Tickets', 'Payroll cost'].contains(metric)) return []
        return dbSql.rows("""WITH line_totals AS (
          SELECT l.order_id AS order_id, sum(l.line_amount) AS line_total
          FROM dash_demo.order_lines l
          GROUP BY l.order_id
        ),
        feed AS (
          -- Revenue at line grain: each order's own total spread over its lines in proportion to what they
          -- cost, so the categories below add up to the number above them.
          SELECT 'Revenue' AS metric,
                 o.order_ts AS happened_at,
                 o.total_amount * l.line_amount / t.line_total AS value,
                 p.category AS made_of,
                 g.country AS country
          FROM dash_demo.order_lines l
          JOIN line_totals t ON t.order_id = l.order_id
          JOIN dash_demo.orders o ON o.order_id = l.order_id
          JOIN dash_demo.products p ON p.product_id = l.product_id
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'Orders', o.order_ts, 1, o.channel, g.country
          FROM dash_demo.orders o
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'New customers', c.signup_date, 1, c.acquisition_channel, g.country
          FROM dash_demo.customers c
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Tickets', tk.opened_ts, 1, tk.category, g.country
          FROM dash_demo.support_tickets tk
          JOIN dash_demo.customers c ON c.customer_id = tk.customer_id
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Payroll cost', pl.period_month,
                 pl.gross_pay + pl.employer_taxes + pl.benefits, d.name, g.country
          FROM dash_demo.payroll_lines pl
          JOIN dash_demo.employees e ON e.employee_id = pl.employee_id
          JOIN dash_demo.departments d ON d.department_id = e.department_id
          JOIN dash_demo.geo_cities g ON g.city_id = e.city_id
        )
        SELECT strftime(f.happened_at, '%m %b') AS month_of_year,
               round(sum(f.value), 2) AS value
        FROM feed f
        WHERE f.metric = ?
        GROUP BY month_of_year
        ORDER BY month_of_year""", [metric])
    }()
    ctx.reportData('chart_dd24-chart-by-month-of-year', chart_dd24_chart_by_month_of_year_data)
}

// ─── Widget: chart_dd24-chart-by-country-top-10 (type=chart, dataSource=script) ───
if (!componentId || componentId == 'chart_dd24-chart-by-country-top-10') {
    def chart_dd24_chart_by_country_top_10_data = { ->
        // The radio's five words are the whole whitelist: the chosen one goes to the database as a value,
        // never as SQL text, so nothing a filter can carry reaches the query itself.
        if (!['Revenue', 'Orders', 'New customers', 'Tickets', 'Payroll cost'].contains(metric)) return []
        return dbSql.rows("""WITH line_totals AS (
          SELECT l.order_id AS order_id, sum(l.line_amount) AS line_total
          FROM dash_demo.order_lines l
          GROUP BY l.order_id
        ),
        feed AS (
          -- Revenue at line grain: each order's own total spread over its lines in proportion to what they
          -- cost, so the categories below add up to the number above them.
          SELECT 'Revenue' AS metric,
                 o.order_ts AS happened_at,
                 o.total_amount * l.line_amount / t.line_total AS value,
                 p.category AS made_of,
                 g.country AS country
          FROM dash_demo.order_lines l
          JOIN line_totals t ON t.order_id = l.order_id
          JOIN dash_demo.orders o ON o.order_id = l.order_id
          JOIN dash_demo.products p ON p.product_id = l.product_id
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'Orders', o.order_ts, 1, o.channel, g.country
          FROM dash_demo.orders o
          JOIN dash_demo.geo_cities g ON g.city_id = o.city_id
          WHERE o.status <> 'cancelled'
          UNION ALL
          SELECT 'New customers', c.signup_date, 1, c.acquisition_channel, g.country
          FROM dash_demo.customers c
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Tickets', tk.opened_ts, 1, tk.category, g.country
          FROM dash_demo.support_tickets tk
          JOIN dash_demo.customers c ON c.customer_id = tk.customer_id
          JOIN dash_demo.geo_cities g ON g.city_id = c.city_id
          UNION ALL
          SELECT 'Payroll cost', pl.period_month,
                 pl.gross_pay + pl.employer_taxes + pl.benefits, d.name, g.country
          FROM dash_demo.payroll_lines pl
          JOIN dash_demo.employees e ON e.employee_id = pl.employee_id
          JOIN dash_demo.departments d ON d.department_id = e.department_id
          JOIN dash_demo.geo_cities g ON g.city_id = e.city_id
        )
        SELECT f.country AS country,
               round(sum(f.value), 2) AS value
        FROM feed f
        WHERE f.metric = ?
          AND f.happened_at >= date_trunc('year', (SELECT a.as_of FROM dash_demo.as_of a))
          AND f.happened_at <= (SELECT a.as_of FROM dash_demo.as_of a)
        GROUP BY f.country
        ORDER BY value DESC
        LIMIT 10""", [metric])
    }()
    ctx.reportData('chart_dd24-chart-by-country-top-10', chart_dd24_chart_by_country_top_10_data)
}

