// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.DateParameters
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// The day after a date: where a range of whole days ends, so that its last day counts
// in full. An empty value stays empty.
def dayAfter = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return DateParameters.nextDay(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def dateFrom = userVars?.get('dateFrom')?.toString()
def hasDateFrom = (dateFrom != null && !dateFrom.isEmpty())
def dateTo = userVars?.get('dateTo')?.toString()
def hasDateTo = (dateTo != null && !dateTo.isEmpty())
def device = userVars?.get('device')?.toString()
def hasDevice = (device != null && !device.isEmpty())
def dateTo__next_day = dayAfter('dateTo', 'Date', dateTo)
def hasDateTo__next_day = (dateTo__next_day != null && !dateTo__next_day.isEmpty())

// ─── Widget: number_estimated_sessions_sessions (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_estimated_sessions_sessions') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) * (SELECT a.web_session_sample_rate FROM dash_demo.as_of a) AS estimated_sessions\n'
    sql << 'FROM dash_demo.web_sessions s\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND s.started_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND s.started_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDevice && listHasValues(device)) {
        addInList(sql, params, device, 'AND s.device IN') { asDeclaredType('device', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_estimated_sessions_sessions', data)
}

// ─── Widget: gauge_conversion_rate_rate (type=gauge, dataSource=sql) ───
if (!componentId || componentId == 'gauge_conversion_rate_rate') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(count(CASE WHEN s.purchased THEN 1 END) * 1.0 / count(*), 4) AS conversion_rate\n'
    sql << 'FROM dash_demo.web_sessions s\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND s.started_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND s.started_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDevice && listHasValues(device)) {
        addInList(sql, params, device, 'AND s.device IN') { asDeclaredType('device', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('gauge_conversion_rate_rate', data)
}

// ─── Widget: trend_started_ts_week (type=trend, dataSource=visual) ───
if (!componentId || componentId == 'trend_started_ts_week') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT *\n'
    sql << 'FROM (\n'
    sql << '  SELECT strftime("started_ts", \'%G-W%V\') AS "started_ts", COUNT("session_id") AS "session_id_count"\n'
    sql << '  FROM "dash_demo"."web_sessions"\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '  WHERE "started_ts" >= ? AND "started_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasDevice && listHasValues(device)) {
        addInList(sql, params, device, 'AND "device" IN') { asDeclaredType('device', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  GROUP BY strftime("started_ts", \'%G-W%V\')\n'
    sql << ') grouped_rows\n'
    sql << 'ORDER BY CASE WHEN "started_ts" IS NULL THEN 1 ELSE 0 END, "started_ts" ASC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('trend_started_ts_week', data)
}

// ─── Widget: chart_dd12-chart-funnel (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd12-chart-funnel') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH scope AS (\n'
    sql << '  SELECT s.reached_product AS reached_product,\n'
    sql << '         s.reached_cart AS reached_cart,\n'
    sql << '         s.reached_checkout AS reached_checkout,\n'
    sql << '         s.purchased AS purchased\n'
    sql << '  FROM dash_demo.web_sessions s\n'
    sql << '  WHERE true\n'
    if (hasDateFrom) {
        sql << '    AND s.started_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '    AND s.started_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasDevice && listHasValues(device)) {
        addInList(sql, params, device, 'AND s.device IN') { asDeclaredType('device', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '),\n'
    sql << 'steps AS (\n'
    sql << '  SELECT 1 AS ord, \'Session\' AS step, count(*) AS sessions FROM scope\n'
    sql << '  UNION ALL SELECT 2, \'Reached product\', count(CASE WHEN reached_product THEN 1 END) FROM scope\n'
    sql << '  UNION ALL SELECT 3, \'Reached cart\', count(CASE WHEN reached_cart THEN 1 END) FROM scope\n'
    sql << '  UNION ALL SELECT 4, \'Reached checkout\', count(CASE WHEN reached_checkout THEN 1 END) FROM scope\n'
    sql << '  UNION ALL SELECT 5, \'Purchased\', count(CASE WHEN purchased THEN 1 END) FROM scope\n'
    sql << ')\n'
    sql << 'SELECT step AS step,\n'
    sql << '       sessions AS sessions,\n'
    sql << '       round(100.0 * sessions / (SELECT max(sessions) FROM steps), 2) AS pct_of_sessions\n'
    sql << 'FROM steps\n'
    sql << 'ORDER BY ord\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd12-chart-funnel', data)
}

// ─── Widget: chart_dd12-chart-sessions-per-week-by-device (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd12-chart-sessions-per-week-by-device') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT *\n'
    sql << 'FROM (\n'
    sql << '  SELECT strftime("started_ts", \'%G-W%V\') AS "started_ts", "device", COUNT("session_id") AS "session_id_count"\n'
    sql << '  FROM "dash_demo"."web_sessions"\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '  WHERE "started_ts" >= ? AND "started_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasDevice && listHasValues(device)) {
        addInList(sql, params, device, 'AND "device" IN') { asDeclaredType('device', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  GROUP BY strftime("started_ts", \'%G-W%V\'), "device"\n'
    sql << ') grouped_rows\n'
    sql << 'ORDER BY CASE WHEN "started_ts" IS NULL THEN 1 ELSE 0 END, "started_ts" ASC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd12-chart-sessions-per-week-by-device', data)
}

// ─── Widget: chart_dd12-chart-mobile-checkout-per-month (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd12-chart-mobile-checkout-per-month') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT strftime(date_trunc(\'month\', s.started_ts), \'%Y-%m\') AS month,\n'
    sql << '       round(100.0 * count(CASE WHEN s.purchased THEN 1 END)\n'
    sql << '             / nullif(count(CASE WHEN s.reached_checkout THEN 1 END), 0), 2) AS checkout_to_purchase_pct,\n'
    sql << '       count(CASE WHEN s.reached_checkout THEN 1 END) AS reached_checkout\n'
    sql << 'FROM dash_demo.web_sessions s\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND s.started_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND s.started_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDevice && listHasValues(device)) {
        addInList(sql, params, device, 'AND s.device IN') { asDeclaredType('device', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd12-chart-mobile-checkout-per-month', data)
}

// ─── Widget: pivot_dd12-pivot-sessions-weekday-hour (type=pivot, dataSource=sql) ───
if (!componentId || componentId == 'pivot_dd12-pivot-sessions-weekday-hour') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT CAST(isodow(s.started_ts) AS VARCHAR) || \' \' || strftime(s.started_ts, \'%a\') AS weekday,\n'
    sql << '       lpad(CAST(hour(s.started_ts) AS VARCHAR), 2, \'0\') AS hour_of_day,\n'
    sql << '       count(*) AS sessions\n'
    sql << 'FROM dash_demo.web_sessions s\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND s.started_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND s.started_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDevice && listHasValues(device)) {
        addInList(sql, params, device, 'AND s.device IN') { asDeclaredType('device', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY 1, 2\n'
    sql << 'ORDER BY 1, 2\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('pivot_dd12-pivot-sessions-weekday-hour', data)
}

// ─── Widget: chart_dd12-chart-conversion-by-traffic-source (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd12-chart-conversion-by-traffic-source') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT s.traffic_source AS traffic_source,\n'
    sql << '       round(100.0 * count(CASE WHEN s.purchased THEN 1 END) / count(*), 2) AS conversion_pct,\n'
    sql << '       count(CASE WHEN s.purchased THEN 1 END) AS purchasing_sessions\n'
    sql << 'FROM dash_demo.web_sessions s\n'
    sql << 'WHERE true\n'
    if (hasDateFrom) {
        sql << '  AND s.started_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND s.started_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDevice && listHasValues(device)) {
        addInList(sql, params, device, 'AND s.device IN') { asDeclaredType('device', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY conversion_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd12-chart-conversion-by-traffic-source', data)
}

