// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.DateParameters
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// The day after a date: where a range of whole days ends, so that its last day counts
// in full. An empty value stays empty.
def dayAfter = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return DateParameters.nextDay(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def dateFrom = userVars?.get('dateFrom')?.toString()
def hasDateFrom = (dateFrom != null && !dateFrom.isEmpty())
def dateTo = userVars?.get('dateTo')?.toString()
def hasDateTo = (dateTo != null && !dateTo.isEmpty())
def country = userVars?.get('country')?.toString()
def hasCountry = (country != null && !country.isEmpty())
def channel = userVars?.get('channel')?.toString()
def hasChannel = (channel != null && !channel.isEmpty())
def dateTo__next_day = dayAfter('dateTo', 'Date', dateTo)
def hasDateTo__next_day = (dateTo__next_day != null && !dateTo__next_day.isEmpty())

// ─── Widget: number_total_amount_sum_revenue (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_total_amount_sum_revenue') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT CAST(SUM("total_amount") AS DECIMAL(31,4)) AS "total_amount_sum"\n'
    sql << 'FROM "dash_demo"."orders"\n'
    sql << 'WHERE "status" <> \'cancelled\'\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '  AND "order_ts" >= ? AND "order_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND "country_code" = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND "channel" IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'LIMIT 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_total_amount_sum_revenue', data)
}

// ─── Widget: number_order_id_count_orders (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_order_id_count_orders') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT COUNT("order_id") AS "order_id_count"\n'
    sql << 'FROM "dash_demo"."orders"\n'
    sql << 'WHERE "status" <> \'cancelled\'\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '  AND "order_ts" >= ? AND "order_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND "country_code" = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND "channel" IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'LIMIT 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_order_id_count_orders', data)
}

// ─── Widget: number_total_amount_avg_value (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_total_amount_avg_value') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT CAST(AVG(CAST("total_amount" AS DECIMAL(31,4))) AS DECIMAL(31,4)) AS "total_amount_avg"\n'
    sql << 'FROM "dash_demo"."orders"\n'
    sql << 'WHERE "status" <> \'cancelled\'\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '  AND "order_ts" >= ? AND "order_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND "country_code" = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND "channel" IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'LIMIT 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_total_amount_avg_value', data)
}

// ─── Widget: number_customer_id_count_distinct_ordered (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_customer_id_count_distinct_ordered') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT COUNT(DISTINCT "customer_id") AS "customer_id_count distinct"\n'
    sql << 'FROM "dash_demo"."orders"\n'
    sql << 'WHERE "status" <> \'cancelled\'\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '  AND "order_ts" >= ? AND "order_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND "country_code" = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND "channel" IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'LIMIT 1\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_customer_id_count_distinct_ordered', data)
}

// ─── Widget: chart_dd02-chart-revenue-per-month (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd02-chart-revenue-per-month') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT *\n'
    sql << 'FROM (\n'
    sql << '  SELECT strftime("order_ts", \'%Y-%m\') AS "order_ts", CAST(SUM("total_amount") AS DECIMAL(31,4)) AS "total_amount_sum"\n'
    sql << '  FROM "dash_demo"."orders"\n'
    sql << '  WHERE "status" <> \'cancelled\'\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '    AND "order_ts" >= ? AND "order_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '    AND "country_code" = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '    AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND "channel" IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  GROUP BY strftime("order_ts", \'%Y-%m\')\n'
    sql << ') grouped_rows\n'
    sql << 'ORDER BY CASE WHEN "order_ts" IS NULL THEN 1 ELSE 0 END, "order_ts" ASC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd02-chart-revenue-per-month', data)
}

// ─── Widget: chart_dd02-chart-revenue-by-category (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd02-chart-revenue-by-category') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT p.category AS category,\n'
    sql << '       ROUND(SUM(l.line_amount), 2) AS revenue\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasDateFrom) {
        sql << '  AND o.order_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.order_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND o.country_code = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND o.channel IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY p.category\n'
    sql << 'ORDER BY revenue DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd02-chart-revenue-by-category', data)
}

// ─── Widget: chart_dd02-chart-revenue-by-channel (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd02-chart-revenue-by-channel') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT "channel", CAST(SUM("total_amount") AS DECIMAL(31,4)) AS "total_amount_sum"\n'
    sql << 'FROM "dash_demo"."orders"\n'
    sql << 'WHERE "status" <> \'cancelled\'\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '  AND "order_ts" >= ? AND "order_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND "country_code" = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND "channel" IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY "channel"\n'
    sql << 'ORDER BY CASE WHEN CAST(SUM("total_amount") AS DECIMAL(31,4)) IS NULL THEN 1 ELSE 0 END, CAST(SUM("total_amount") AS DECIMAL(31,4)) DESC\n'
    sql << 'LIMIT 50\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd02-chart-revenue-by-channel', data)
}

// ─── Widget: map_dd02-map-revenue-by-country (type=map, dataSource=visual) ───
if (!componentId || componentId == 'map_dd02-map-revenue-by-country') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT "country_code", CAST(SUM("total_amount") AS DECIMAL(31,4)) AS "total_amount_sum"\n'
    sql << 'FROM "dash_demo"."orders"\n'
    sql << 'WHERE "status" <> \'cancelled\'\n'
    if (hasDateFrom && hasDateTo__next_day) {
        sql << '  AND "order_ts" >= ? AND "order_ts" < ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND "country_code" = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND "channel" IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY "country_code"\n'
    sql << 'ORDER BY CASE WHEN CAST(SUM("total_amount") AS DECIMAL(31,4)) IS NULL THEN 1 ELSE 0 END, CAST(SUM("total_amount") AS DECIMAL(31,4)) DESC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('map_dd02-map-revenue-by-country', data)
}

// ─── Widget: tabulator_dd02-table-top-products (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd02-table-top-products') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT p.name AS product,\n'
    sql << '       p.category AS category,\n'
    sql << '       SUM(l.qty) AS quantity,\n'
    sql << '       ROUND(SUM(l.line_amount), 2) AS revenue\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasDateFrom) {
        sql << '  AND o.order_ts >= ?\n'
        params << asDeclaredType('dateFrom', 'Date', dateFrom)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasDateTo__next_day) {
        sql << '  AND o.order_ts < ?\n'
        params << asDeclaredType('dateTo__next_day', 'Date', dateTo__next_day)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCountry) {
        sql << '  AND o.country_code = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasChannel && listHasValues(channel)) {
        addInList(sql, params, channel, 'AND o.channel IN') { asDeclaredType('channel', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY p.name, p.category\n'
    sql << 'ORDER BY revenue DESC\n'
    sql << 'LIMIT 20\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd02-table-top-products', data)
}

