// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def customerType = userVars?.get('customerType')?.toString()
def hasCustomerType = (customerType != null && !customerType.isEmpty())

// ─── Widget: pivot_dd10-pivot-cohorts (type=pivot, dataSource=sql) ───
if (!componentId || componentId == 'pivot_dd10-pivot-cohorts') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH base AS (\n'
    sql << '  SELECT c.customer_id AS customer_id,\n'
    sql << '         c.signup_date AS signup_date,\n'
    if (hasCustomerType) {
        sql << '         CASE WHEN ? = \'business\'\n'
        params << asDeclaredType('customerType', 'String', customerType)
    }
    sql << '              THEN CAST(year(c.signup_date) AS VARCHAR) || \' Q\' || CAST(quarter(c.signup_date) AS VARCHAR)\n'
    sql << '              ELSE strftime(date_trunc(\'month\', c.signup_date), \'%Y-%m\') END AS cohort,\n'
    if (hasCustomerType) {
        sql << '         CASE WHEN ? = \'business\' THEN 3 ELSE 1 END AS step\n'
        params << asDeclaredType('customerType', 'String', customerType)
    }
    sql << '  FROM dash_demo.customers c\n'
    sql << '  WHERE true\n'
    if (hasCustomerType) {
        sql << '  AND (? = \'all\' OR c.customer_type = ?)\n'
        params << asDeclaredType('customerType', 'String', customerType)
        params << asDeclaredType('customerType', 'String', customerType)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '),\n'
    sql << 'periods AS (SELECT unnest(range(1, 13)) AS n)\n'
    sql << 'SELECT b.cohort AS cohort,\n'
    sql << '       lpad(CAST(p.n AS VARCHAR), 2, \'0\') AS periods_since_signup,\n'
    sql << '       round(100.0 * count(DISTINCT CASE WHEN EXISTS (SELECT 1 FROM dash_demo.orders o\n'
    sql << '                                  WHERE o.customer_id = b.customer_id\n'
    sql << '                                    AND o.status <> \'cancelled\'\n'
    sql << '                                    AND o.order_ts >= b.signup_date + (p.n - 1) * b.step * INTERVAL 1 MONTH\n'
    sql << '                                    AND o.order_ts < b.signup_date + (p.n + 1) * b.step * INTERVAL 1 MONTH)\n'
    sql << '                                THEN b.customer_id END)\n'
    sql << '                   / count(DISTINCT b.customer_id), 2) AS retention_pct\n'
    sql << 'FROM base b\n'
    sql << 'CROSS JOIN periods p\n'
    sql << 'GROUP BY 1, 2\n'
    sql << 'ORDER BY 1, 2\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('pivot_dd10-pivot-cohorts', data)
}

// ─── Widget: chart_dd10-chart-retention-curve (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd10-chart-retention-curve') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH base AS (\n'
    sql << '  SELECT c.customer_id AS customer_id,\n'
    sql << '         c.signup_date AS signup_date,\n'
    sql << '         1 AS step,\n'
    sql << '         CASE WHEN c.signup_date < DATE \'2025-03-01\' THEN \'before March 2025\'\n'
    sql << '              ELSE \'from March 2025\' END AS cohort_group\n'
    sql << '  FROM dash_demo.customers c\n'
    sql << '  WHERE ((c.signup_date >= DATE \'2024-03-01\' AND c.signup_date < DATE \'2025-01-01\')\n'
    sql << '      OR (c.signup_date >= DATE \'2025-03-01\' AND c.signup_date < DATE \'2026-01-01\'))\n'
    if (hasCustomerType) {
        sql << '  AND (? = \'all\' OR c.customer_type = ?)\n'
        params << asDeclaredType('customerType', 'String', customerType)
        params << asDeclaredType('customerType', 'String', customerType)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << '),\n'
    sql << 'periods AS (SELECT unnest(range(1, 13)) AS n)\n'
    sql << 'SELECT p.n AS month_since_signup,\n'
    sql << '       b.cohort_group AS cohort_group,\n'
    sql << '       round(100.0 * count(DISTINCT CASE WHEN EXISTS (SELECT 1 FROM dash_demo.orders o\n'
    sql << '                                  WHERE o.customer_id = b.customer_id\n'
    sql << '                                    AND o.status <> \'cancelled\'\n'
    sql << '                                    AND o.order_ts >= b.signup_date + (p.n - 1) * b.step * INTERVAL 1 MONTH\n'
    sql << '                                    AND o.order_ts < b.signup_date + (p.n + 1) * b.step * INTERVAL 1 MONTH)\n'
    sql << '                                THEN b.customer_id END)\n'
    sql << '                   / count(DISTINCT b.customer_id), 2) AS retention_pct\n'
    sql << 'FROM base b\n'
    sql << 'CROSS JOIN periods p\n'
    sql << 'GROUP BY 1, 2\n'
    sql << 'ORDER BY 1, 2\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd10-chart-retention-curve', data)
}

// ─── Widget: number_retention_pct_retention (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_retention_pct_retention') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(1.0 * count(CASE WHEN EXISTS (SELECT 1 FROM dash_demo.orders o\n'
    sql << '                                           WHERE o.customer_id = c.customer_id\n'
    sql << '                                             AND o.status <> \'cancelled\'\n'
    sql << '                                             AND o.order_ts >= c.signup_date + INTERVAL 5 MONTH\n'
    sql << '                                             AND o.order_ts < c.signup_date + INTERVAL 7 MONTH)\n'
    sql << '                          THEN 1 END) / count(*), 4) AS retention_pct\n'
    sql << 'FROM dash_demo.customers c\n'
    sql << 'WHERE c.signup_date >= DATE \'2024-01-01\'\n'
    sql << '  AND c.signup_date < DATE \'2026-04-01\'\n'
    if (hasCustomerType) {
        sql << '  AND (? = \'all\' OR c.customer_type = ?)\n'
        params << asDeclaredType('customerType', 'String', customerType)
        params << asDeclaredType('customerType', 'String', customerType)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_retention_pct_retention', data)
}

