// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def country = userVars?.get('country')?.toString()
def hasCountry = (country != null && !country.isEmpty())

// ─── Widget: number_netsales_net (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_netsales_net') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  CAST(SUM(CASE WHEN (cube_demo.shop_orders.status NOT IN (\'Cancelled\', \'Returned\')) THEN cube_demo.shop_order_lines.qty * cube_demo.shop_order_lines.unit_price * (100 - cube_demo.shop_order_lines.discount_pct) * 0.01 END) AS DECIMAL(31,4)) AS "NetSales"\n'
    sql << 'FROM cube_demo.shop_orders\n'
    sql << 'LEFT JOIN cube_demo.shop_order_lines ON cube_demo.shop_orders.order_id = cube_demo.shop_order_lines.order_id\n'
    sql << 'LEFT JOIN cube_demo.shop_customers ON cube_demo.shop_orders.customer_id = cube_demo.shop_customers.customer_id\n'
    sql << 'WHERE cube_demo.shop_orders.status NOT IN (\'Cancelled\', \'Returned\')\n'
    if (hasCountry && listHasValues(country)) {
        addInList(sql, params, country, 'AND cube_demo.shop_customers.country IN') { asDeclaredType('country', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_netsales_net', data)
}

// ─── Widget: number_units_units (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_units_units') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  CAST(SUM(cube_demo.shop_order_lines.qty) AS DECIMAL(31,4)) AS "Units"\n'
    sql << 'FROM cube_demo.shop_orders\n'
    sql << 'LEFT JOIN cube_demo.shop_order_lines ON cube_demo.shop_orders.order_id = cube_demo.shop_order_lines.order_id\n'
    sql << 'LEFT JOIN cube_demo.shop_customers ON cube_demo.shop_orders.customer_id = cube_demo.shop_customers.customer_id\n'
    sql << 'WHERE cube_demo.shop_orders.status NOT IN (\'Cancelled\', \'Returned\')\n'
    if (hasCountry && listHasValues(country)) {
        addInList(sql, params, country, 'AND cube_demo.shop_customers.country IN') { asDeclaredType('country', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_units_units', data)
}

// ─── Widget: chart_channel_channel (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_channel_channel') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  cube_demo.shop_orders.channel AS "Channel",\n'
    sql << '  COUNT(*) AS "Orders"\n'
    sql << 'FROM cube_demo.shop_orders\n'
    sql << 'LEFT JOIN cube_demo.shop_customers ON cube_demo.shop_orders.customer_id = cube_demo.shop_customers.customer_id\n'
    sql << 'WHERE cube_demo.shop_orders.status NOT IN (\'Cancelled\', \'Returned\')\n'
    if (hasCountry && listHasValues(country)) {
        addInList(sql, params, country, 'AND cube_demo.shop_customers.country IN') { asDeclaredType('country', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY\n'
    sql << '  cube_demo.shop_orders.channel\n'
    sql << 'ORDER BY\n'
    sql << '  "Orders" DESC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_channel_channel', data)
}

// ─── Widget: tabulator_net-category (type=tabulator, dataSource=visual) ───
if (!componentId || componentId == 'tabulator_net-category') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  cube_demo.shop_products.category AS "Category",\n'
    sql << '  CAST(SUM(CASE WHEN (cube_demo.shop_orders.status NOT IN (\'Cancelled\', \'Returned\')) THEN cube_demo.shop_order_lines.qty * cube_demo.shop_order_lines.unit_price * (100 - cube_demo.shop_order_lines.discount_pct) * 0.01 END) AS DECIMAL(31,4)) AS "NetSales"\n'
    sql << 'FROM cube_demo.shop_orders\n'
    sql << 'LEFT JOIN cube_demo.shop_order_lines ON cube_demo.shop_orders.order_id = cube_demo.shop_order_lines.order_id\n'
    sql << 'LEFT JOIN cube_demo.shop_products ON cube_demo.shop_order_lines.product_id = cube_demo.shop_products.product_id\n'
    sql << 'LEFT JOIN cube_demo.shop_customers ON cube_demo.shop_orders.customer_id = cube_demo.shop_customers.customer_id\n'
    sql << 'WHERE cube_demo.shop_orders.status NOT IN (\'Cancelled\', \'Returned\')\n'
    if (hasCountry && listHasValues(country)) {
        addInList(sql, params, country, 'AND cube_demo.shop_customers.country IN') { asDeclaredType('country', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY\n'
    sql << '  cube_demo.shop_products.category\n'
    sql << 'ORDER BY\n'
    sql << '  "NetSales" DESC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_net-category', data)
}

