// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.DateParameters
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// The day after a date: where a range of whole days ends, so that its last day counts
// in full. An empty value stays empty.
def dayAfter = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return DateParameters.nextDay(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def status = userVars?.get('status')?.toString()
def hasStatus = (status != null && !status.isEmpty())
def customerId = userVars?.get('customerId')?.toString()
def hasCustomerId = (customerId != null && !customerId.isEmpty())
def issuedFrom = userVars?.get('issuedFrom')?.toString()
def hasIssuedFrom = (issuedFrom != null && !issuedFrom.isEmpty())
def issuedTo = userVars?.get('issuedTo')?.toString()
def hasIssuedTo = (issuedTo != null && !issuedTo.isEmpty())
def issuedTo__next_day = dayAfter('issuedTo', 'Date', issuedTo)
def hasIssuedTo__next_day = (issuedTo__next_day != null && !issuedTo__next_day.isEmpty())

// ─── Widget: number_billed_this_month_month (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_billed_this_month_month') {
    def sql = new StringBuilder()
    sql << 'SELECT round(sum(i.amount + i.tax_amount), 2) AS billed_this_month\n'
    sql << 'FROM dash_demo.invoices i\n'
    sql << 'WHERE date_trunc(\'month\', i.issue_date) = date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a))\n'
    def data = dbSql.rows(sql.toString())
    ctx.reportData('number_billed_this_month_month', data)
}

// ─── Widget: number_collected_this_month_month (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_collected_this_month_month') {
    def sql = new StringBuilder()
    sql << 'SELECT round(sum(p.amount), 2) AS collected_this_month\n'
    sql << 'FROM dash_demo.invoice_payments p\n'
    sql << 'WHERE date_trunc(\'month\', p.paid_date) = date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a))\n'
    def data = dbSql.rows(sql.toString())
    ctx.reportData('number_collected_this_month_month', data)
}

// ─── Widget: number_openamount_amount (type=number, dataSource=visual) ───
if (!componentId || componentId == 'number_openamount_amount') {
    def sql = new StringBuilder()
    sql << 'SELECT\n'
    sql << '  CAST(SUM(CASE WHEN (dash_demo.invoices.status IN (\'open\', \'overdue\', \'partially_paid\')) THEN dash_demo.invoices.amount + dash_demo.invoices.tax_amount END) AS DECIMAL(31,4)) AS "OpenAmount"\n'
    sql << 'FROM dash_demo.invoices\n'
    def data = dbSql.rows(sql.toString())
    ctx.reportData('number_openamount_amount', data)
}

// ─── Widget: number_overdue_amount_amount (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_overdue_amount_amount') {
    def sql = new StringBuilder()
    sql << 'SELECT round(sum(i.amount + i.tax_amount), 2) AS overdue_amount\n'
    sql << 'FROM dash_demo.invoices i\n'
    sql << 'WHERE i.status = \'overdue\'\n'
    def data = dbSql.rows(sql.toString())
    ctx.reportData('number_overdue_amount_amount', data)
}

// ─── Widget: chart_dd13-chart-billed-per-month-by-status (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd13-chart-billed-per-month-by-status') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  CAST(DATE_TRUNC(\'month\', dash_demo.invoices.issue_date) AS DATE) AS "IssuedAt",\n'
    sql << '  dash_demo.invoices.status AS "Status",\n'
    sql << '  CAST(SUM(dash_demo.invoices.amount + dash_demo.invoices.tax_amount) AS DECIMAL(31,4)) AS "Billed"\n'
    sql << 'FROM dash_demo.invoices\n'
    if (hasIssuedFrom && hasIssuedTo) {
        sql << 'WHERE (dash_demo.invoices.issue_date >= ? AND dash_demo.invoices.issue_date <= ?)\n'
        params << asDeclaredType('issuedFrom', 'Date', issuedFrom)
        params << asDeclaredType('issuedTo', 'Date', issuedTo)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasStatus && listHasValues(status)) {
        addInList(sql, params, status, 'AND dash_demo.invoices.status IN') { asDeclaredType('status', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY\n'
    sql << '  CAST(DATE_TRUNC(\'month\', dash_demo.invoices.issue_date) AS DATE),\n'
    sql << '  dash_demo.invoices.status\n'
    sql << 'ORDER BY\n'
    sql << '  "IssuedAt" ASC,\n'
    sql << '  "Status" ASC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd13-chart-billed-per-month-by-status', data)
}

// ─── Widget: chart_dd13-chart-billed-by-source (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd13-chart-billed-by-source') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT "source", (100.0 * CAST(CAST(SUM(("amount" + "tax_amount")) AS DECIMAL(31,4)) AS DECIMAL(20,4)) / NULLIF(SUM(CAST(SUM(("amount" + "tax_amount")) AS DECIMAL(31,4))) OVER (), 0)) AS "billed_sum_pct"\n'
    sql << 'FROM "dash_demo"."invoices"\n'
    if (hasIssuedFrom && hasIssuedTo__next_day) {
        sql << 'WHERE "issue_date" >= ? AND "issue_date" < ?\n'
        params << asDeclaredType('issuedFrom', 'Date', issuedFrom)
        params << asDeclaredType('issuedTo__next_day', 'Date', issuedTo__next_day)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasStatus && listHasValues(status)) {
        addInList(sql, params, status, 'AND "status" IN') { asDeclaredType('status', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasCustomerId) {
        sql << '  AND "customer_id" = ?\n'
        params << asDeclaredType('customerId', 'Integer', customerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY "source"\n'
    sql << 'ORDER BY CASE WHEN CAST(SUM(("amount" + "tax_amount")) AS DECIMAL(31,4)) IS NULL THEN 1 ELSE 0 END, CAST(SUM(("amount" + "tax_amount")) AS DECIMAL(31,4)) DESC\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd13-chart-billed-by-source', data)
}

// ─── Widget: chart_dd13-chart-top-10-customers-by-billed (type=chart, dataSource=visual) ───
if (!componentId || componentId == 'chart_dd13-chart-top-10-customers-by-billed') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT\n'
    sql << '  dash_demo.customers.name AS "Customer",\n'
    sql << '  CAST(SUM(dash_demo.invoices.amount + dash_demo.invoices.tax_amount) AS DECIMAL(31,4)) AS "Billed"\n'
    sql << 'FROM dash_demo.invoices\n'
    sql << 'LEFT JOIN dash_demo.customers ON dash_demo.invoices.customer_id = dash_demo.customers.customer_id\n'
    if (hasIssuedFrom && hasIssuedTo) {
        sql << 'WHERE (dash_demo.invoices.issue_date >= ? AND dash_demo.invoices.issue_date <= ?)\n'
        params << asDeclaredType('issuedFrom', 'Date', issuedFrom)
        params << asDeclaredType('issuedTo', 'Date', issuedTo)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasStatus && listHasValues(status)) {
        addInList(sql, params, status, 'AND dash_demo.invoices.status IN') { asDeclaredType('status', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << 'GROUP BY\n'
    sql << '  dash_demo.customers.name\n'
    sql << 'ORDER BY\n'
    sql << '  "Billed" DESC\n'
    sql << 'LIMIT 10\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd13-chart-top-10-customers-by-billed', data)
}

// ─── Widget: tabulator_invoices_invoices (type=tabulator, dataSource=visual) ───
if (!componentId || componentId == 'tabulator_invoices_invoices') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT *\n'
    sql << 'FROM "dash_demo"."invoices"\n'
    if (hasIssuedFrom && hasIssuedTo__next_day) {
        sql << 'WHERE "issue_date" >= ? AND "issue_date" < ?\n'
        params << asDeclaredType('issuedFrom', 'Date', issuedFrom)
        params << asDeclaredType('issuedTo__next_day', 'Date', issuedTo__next_day)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    if (hasStatus && listHasValues(status)) {
        addInList(sql, params, status, 'AND "status" IN') { asDeclaredType('status', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasCustomerId) {
        sql << '  AND "customer_id" = ?\n'
        params << asDeclaredType('customerId', 'Integer', customerId)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'ORDER BY CASE WHEN "issue_date" IS NULL THEN 1 ELSE 0 END, "issue_date" DESC\n'
    sql << 'LIMIT 5000\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_invoices_invoices', data)
}

