// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// A list filter is off when it has no values, or when it is '*' (all values).
def listHasValues = { listValue ->
    def text = listValue.toString().trim()
    if (text == '*') {
        return false
    }
    return text.split(',').any { it.trim() }
}

// A list item with no declared type is sent as a whole number, a decimal or text,
// whichever it reads as.
def numberOrText = { String item ->
    try {
        return Long.parseLong(item)
    } catch (NumberFormatException notWhole) {
        try {
            return Double.parseDouble(item)
        } catch (NumberFormatException notANumber) {
            return item
        }
    }
}

// Adds the line with its list, `... IN (?, ?, ?)`, one ? per comma-separated item, and
// sends the items as the values of those ?s: each through `convert` when one is given.
// A list with no items still gets one, an empty one, which matches no row: that only
// happens for a list the server sets for the viewer, such as their groups.
def addInList = { sql, params, listValue, lineBeforeList, convert = null ->
    def items = (listValue ?: '').toString().split(',').collect { it.trim() }.findAll { it }
    if (items.isEmpty()) {
        items = ['']
    }
    sql << lineBeforeList + ' (' + items.collect { '?' }.join(', ') + ')\n'
    items.each { item ->
        params << (convert ? convert(item) : numberOrText(item))
    }
}

// ─── Filter values: an empty one turns its filter off ───
def warehouse = userVars?.get('warehouse')?.toString()
def hasWarehouse = (warehouse != null && !warehouse.isEmpty())
def belowReorderOnly = userVars?.get('belowReorderOnly')?.toString()
def hasBelowReorderOnly = (belowReorderOnly != null && !belowReorderOnly.isEmpty())
def category = userVars?.get('category')?.toString()
def hasCategory = (category != null && !category.isEmpty())

// ─── Widget: number_stock_value_value (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_stock_value_value') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(sl.qty_on_hand * pr.unit_cost), 2) AS stock_value\n'
    sql << 'FROM dash_demo.stock_levels sl\n'
    sql << 'JOIN dash_demo.products pr ON pr.product_id = sl.product_id\n'
    sql << 'JOIN dash_demo.warehouses w ON w.warehouse_id = sl.warehouse_id\n'
    sql << 'WHERE true\n'
    if (hasWarehouse) {
        sql << '  AND w.name = ?\n'
        params << asDeclaredType('warehouse', 'String', warehouse)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory && listHasValues(category)) {
        addInList(sql, params, category, 'AND pr.category IN') { asDeclaredType('category', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_stock_value_value', data)
}

// ─── Widget: number_skus_below_reorder_reorder (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_skus_below_reorder_reorder') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT count(*) AS skus_below_reorder\n'
    sql << 'FROM dash_demo.stock_levels sl\n'
    sql << 'JOIN dash_demo.products pr ON pr.product_id = sl.product_id\n'
    sql << 'JOIN dash_demo.warehouses w ON w.warehouse_id = sl.warehouse_id\n'
    sql << 'WHERE true\n'
    if (hasWarehouse) {
        sql << '  AND w.name = ?\n'
        params << asDeclaredType('warehouse', 'String', warehouse)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory && listHasValues(category)) {
        addInList(sql, params, category, 'AND pr.category IN') { asDeclaredType('category', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  AND sl.qty_on_hand < sl.reorder_level\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_skus_below_reorder_reorder', data)
}

// ─── Widget: number_slow_mover_value_value (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_slow_mover_value_value') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(sum(sl.qty_on_hand * pr.unit_cost), 2) AS slow_mover_value\n'
    sql << 'FROM dash_demo.stock_levels sl\n'
    sql << 'JOIN dash_demo.products pr ON pr.product_id = sl.product_id\n'
    sql << 'JOIN dash_demo.warehouses w ON w.warehouse_id = sl.warehouse_id\n'
    sql << 'WHERE true\n'
    if (hasWarehouse) {
        sql << '  AND w.name = ?\n'
        params << asDeclaredType('warehouse', 'String', warehouse)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory && listHasValues(category)) {
        addInList(sql, params, category, 'AND pr.category IN') { asDeclaredType('category', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  AND (sl.last_sold_date IS NULL OR sl.last_sold_date < (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 90 DAY)\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_slow_mover_value_value', data)
}

// ─── Widget: chart_dd19-chart-space-used-by-warehouse (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd19-chart-space-used-by-warehouse') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT w.name AS warehouse,\n'
    sql << '       round(100.0 * sum(sl.qty_on_hand) / max(w.capacity_units), 2) AS capacity_pct\n'
    sql << 'FROM dash_demo.stock_levels sl\n'
    sql << 'JOIN dash_demo.warehouses w ON w.warehouse_id = sl.warehouse_id\n'
    sql << 'WHERE true\n'
    if (hasWarehouse) {
        sql << '  AND w.name = ?\n'
        params << asDeclaredType('warehouse', 'String', warehouse)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY w.name\n'
    sql << 'ORDER BY capacity_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd19-chart-space-used-by-warehouse', data)
}

// ─── Widget: chart_dd19-chart-slow-movers-by-value (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd19-chart-slow-movers-by-value') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT pr.sku || \' \' || pr.name AS product,\n'
    sql << '       round(sum(sl.qty_on_hand * pr.unit_cost), 2) AS stuck_value\n'
    sql << 'FROM dash_demo.stock_levels sl\n'
    sql << 'JOIN dash_demo.products pr ON pr.product_id = sl.product_id\n'
    sql << 'JOIN dash_demo.warehouses w ON w.warehouse_id = sl.warehouse_id\n'
    sql << 'WHERE true\n'
    if (hasWarehouse) {
        sql << '  AND w.name = ?\n'
        params << asDeclaredType('warehouse', 'String', warehouse)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory && listHasValues(category)) {
        addInList(sql, params, category, 'AND pr.category IN') { asDeclaredType('category', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    sql << '  AND (sl.last_sold_date IS NULL OR sl.last_sold_date < (SELECT a.as_of FROM dash_demo.as_of a) - INTERVAL 90 DAY)\n'
    sql << 'GROUP BY pr.sku, pr.name\n'
    sql << 'ORDER BY stuck_value DESC\n'
    sql << 'LIMIT 10\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd19-chart-slow-movers-by-value', data)
}

// ─── Widget: tabulator_dd19-table-stock-by-sku (type=tabulator, dataSource=sql) ───
if (!componentId || componentId == 'tabulator_dd19-table-stock-by-sku') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT pr.sku AS sku,\n'
    sql << '       pr.name AS product,\n'
    sql << '       pr.category AS category,\n'
    sql << '       w.name AS warehouse,\n'
    sql << '       sl.qty_on_hand AS qty_on_hand,\n'
    sql << '       sl.reorder_level AS reorder_level,\n'
    sql << '       greatest(sl.reorder_level - sl.qty_on_hand, sl.reorder_qty) AS suggested_order\n'
    sql << 'FROM dash_demo.stock_levels sl\n'
    sql << 'JOIN dash_demo.products pr ON pr.product_id = sl.product_id\n'
    sql << 'JOIN dash_demo.warehouses w ON w.warehouse_id = sl.warehouse_id\n'
    sql << 'WHERE true\n'
    if (hasWarehouse) {
        sql << '  AND w.name = ?\n'
        params << asDeclaredType('warehouse', 'String', warehouse)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    if (hasCategory && listHasValues(category)) {
        addInList(sql, params, category, 'AND pr.category IN') { asDeclaredType('category', 'String', it) }
    } else {
        sql << 'AND 1=1\n'   // no values, or '*' (all): this filter is off
    }
    if (hasBelowReorderOnly) {
        sql << '  AND (sl.qty_on_hand < sl.reorder_level OR NOT ?)\n'
        params << asDeclaredType('belowReorderOnly', 'Boolean', belowReorderOnly)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'ORDER BY suggested_order DESC, pr.sku\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_dd19-table-stock-by-sku', data)
}

