// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def category = userVars?.get('category')?.toString()
def hasCategory = (category != null && !category.isEmpty())
def topN = userVars?.get('topN')?.toString()
def hasTopN = (topN != null && !topN.isEmpty())

// ─── Widget: chart_dd05-chart-rating-vs-units (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd05-chart-rating-vs-units') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT p.rating AS rating,\n'
    sql << '       sum(l.qty) AS units,\n'
    sql << '       p.name AS product\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasCategory) {
        sql << '  AND p.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1, 3\n'
    sql << 'ORDER BY rating\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd05-chart-rating-vs-units', data)
}

// ─── Widget: chart_dd05-chart-discount-vs-return-rate (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd05-chart-discount-vs-return-rate') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT p.name AS product,\n'
    sql << '       round(avg(l.discount_pct), 2) AS discount_pct,\n'
    sql << '       round(100.0 * count(DISTINCT CASE WHEN o.status = \'returned\' THEN o.order_id END)\n'
    sql << '             / count(DISTINCT o.order_id), 2) AS return_rate_pct,\n'
    sql << '       round(sum(l.line_amount), 2) AS revenue,\n'
    sql << '       round(4 + 20.0 * sum(l.line_amount) / max(sum(l.line_amount)) OVER (), 1) AS bubble_size\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.order_ts >= date_trunc(\'month\', (SELECT a.as_of FROM dash_demo.as_of a)) - INTERVAL 5 MONTH\n'
    if (hasCategory) {
        sql << '  AND p.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY return_rate_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd05-chart-discount-vs-return-rate', data)
}

// ─── Widget: chart_dd05-chart-top-n-by-margin (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd05-chart-top-n-by-margin') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT p.name AS product,\n'
    sql << '       round(sum(l.line_amount - l.line_cost), 2) AS gross_margin\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasCategory) {
        sql << '  AND p.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY gross_margin DESC\n'
    if (hasTopN) {
        sql << 'LIMIT ?\n'
        params << asDeclaredType('topN', 'Integer', topN)
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd05-chart-top-n-by-margin', data)
}

// ─── Widget: chart_dd05-chart-bottom-n-by-margin (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd05-chart-bottom-n-by-margin') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT p.name AS product,\n'
    sql << '       round(sum(l.line_amount - l.line_cost), 2) AS gross_margin\n'
    sql << 'FROM dash_demo.order_lines l\n'
    sql << 'JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasCategory) {
        sql << '  AND p.category = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY gross_margin ASC\n'
    if (hasTopN) {
        sql << 'LIMIT ?\n'
        params << asDeclaredType('topN', 'Integer', topN)
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd05-chart-bottom-n-by-margin', data)
}

// ─── Widget: tabulator_products_products (type=tabulator, dataSource=visual) ───
if (!componentId || componentId == 'tabulator_products_products') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT *\n'
    sql << 'FROM "dash_demo"."products"\n'
    if (hasCategory) {
        sql << 'WHERE "category" = ?\n'
        params << asDeclaredType('category', 'String', category)
    } else {
        sql << 'WHERE 1=1\n'   // no value: this filter is off
    }
    sql << 'ORDER BY CASE WHEN "name" IS NULL THEN 1 ELSE 0 END, "name" asc\n'
    sql << 'LIMIT 500\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('tabulator_products_products', data)
}

