// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def includeReturns = userVars?.get('includeReturns')?.toString()
def hasIncludeReturns = (includeReturns != null && !includeReturns.isEmpty())

// ─── Widget: chart_dd04-chart-revenue-mix-by-channel (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd04-chart-revenue-mix-by-channel') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.channel AS channel,\n'
    sql << '       round(sum(o.total_amount), 2) AS revenue,\n'
    sql << '       round(100.0 * sum(o.total_amount) / sum(sum(o.total_amount)) OVER (), 2) AS share_pct\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasIncludeReturns) {
        sql << '  AND (o.status <> \'returned\' OR ?)\n'
        params << asDeclaredType('includeReturns', 'Boolean', includeReturns)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY revenue DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd04-chart-revenue-mix-by-channel', data)
}

// ─── Widget: chart_dd04-chart-average-order-value-per-channel (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd04-chart-average-order-value-per-channel') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.channel AS channel,\n'
    sql << '       round(avg(o.total_amount), 2) AS avg_order_value,\n'
    sql << '       count(*) AS orders\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasIncludeReturns) {
        sql << '  AND (o.status <> \'returned\' OR ?)\n'
        params << asDeclaredType('includeReturns', 'Boolean', includeReturns)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1\n'
    sql << 'ORDER BY avg_order_value DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd04-chart-average-order-value-per-channel', data)
}

// ─── Widget: chart_dd04-chart-channel-share-per-month (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd04-chart-channel-share-per-month') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT date_trunc(\'month\', o.order_ts) AS month,\n'
    sql << '       o.channel AS channel,\n'
    sql << '       round(100.0 * count(*)\n'
    sql << '             / sum(count(*)) OVER (PARTITION BY date_trunc(\'month\', o.order_ts)), 2) AS share_pct\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasIncludeReturns) {
        sql << '  AND (o.status <> \'returned\' OR ?)\n'
        params << asDeclaredType('includeReturns', 'Boolean', includeReturns)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1, 2\n'
    sql << 'ORDER BY 1, 2\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd04-chart-channel-share-per-month', data)
}

// ─── Widget: sankey_channel_category (type=sankey, dataSource=sql) ───
if (!componentId || componentId == 'sankey_channel_category') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.channel AS channel,\n'
    sql << '       p.category AS category,\n'
    sql << '       round(sum(l.line_amount), 2) AS revenue\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.order_lines l ON l.order_id = o.order_id\n'
    sql << 'JOIN dash_demo.products p ON p.product_id = l.product_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasIncludeReturns) {
        sql << '  AND (o.status <> \'returned\' OR ?)\n'
        params << asDeclaredType('includeReturns', 'Boolean', includeReturns)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY 1, 2\n'
    sql << 'ORDER BY revenue DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('sankey_channel_category', data)
}

