// AUTO-GENERATED by CanvasExportService. DO NOT EDIT MANUALLY.
// Regenerated on every Save-to-DataPallas.
//
// Fetches the data of the dashboard's widgets, one block per widget. An SQL widget builds its
// query line by line, and every value reaches the database as a ? parameter, never pasted
// into the SQL text.

import groovy.sql.Sql
import com.sourcekraft.documentburster.common.reportparameters.ParameterTypes

// componentId names the one widget asking for its data (none: every widget).
// userVars holds the filter values, and the values the server sets for the viewer.
def dbSql       = ctx.dbSql
def componentId = ctx.variables?.get('componentId')
def userVars    = ctx.variables.getUserVariables(ctx.token ?: '')

// Converts a filter value from text to the type the dashboard declared for it (Date,
// Integer, ...), so the database compares a date with a date and a number with a number.
// An empty value stays empty.
def asDeclaredType = { String name, String type, value ->
    if (value == null || value.toString().isEmpty()) {
        return value
    }
    return ParameterTypes.typed(name, type, value.toString())
}

// ─── Filter values: an empty one turns its filter off ───
def country = userVars?.get('country')?.toString()
def hasCountry = (country != null && !country.isEmpty())

// ─── Widget: number_aov_here_here (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_aov_here_here') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(avg(o.total_amount), 2) AS aov_here\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_aov_here_here', data)
}

// ─── Widget: number_aov_everywhere_everywhere (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_aov_everywhere_everywhere') {
    def sql = new StringBuilder()
    sql << 'SELECT round(avg(o.total_amount), 2) AS aov_everywhere\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'WHERE o.status <> \'cancelled\'\n'
    def data = dbSql.rows(sql.toString())
    ctx.reportData('number_aov_everywhere_everywhere', data)
}

// ─── Widget: number_return_rate_here_here (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_return_rate_here_here') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT round(count(CASE WHEN o.status = \'returned\' THEN 1 END)\n'
    sql << '             / count(*)::DOUBLE, 4) AS return_rate_here\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << 'WHERE true\n'
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('number_return_rate_here_here', data)
}

// ─── Widget: number_return_rate_everywhere_everywhere (type=number, dataSource=sql) ───
if (!componentId || componentId == 'number_return_rate_everywhere_everywhere') {
    def sql = new StringBuilder()
    sql << 'SELECT round(count(CASE WHEN o.status = \'returned\' THEN 1 END)\n'
    sql << '             / count(*)::DOUBLE, 4) AS return_rate_everywhere\n'
    sql << 'FROM dash_demo.orders o\n'
    def data = dbSql.rows(sql.toString())
    ctx.reportData('number_return_rate_everywhere_everywhere', data)
}

// ─── Widget: chart_dd25-chart-category-share-here-vs-everyone (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd25-chart-category-share-here-vs-everyone') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH per_category AS (\n'
    sql << '  SELECT pr.category AS category,\n'
    if (hasCountry) {
        sql << '         sum(CASE WHEN g.country = ? THEN l.line_amount ELSE 0 END) AS here,\n'
        params << asDeclaredType('country', 'String', country)
    }
    sql << '         sum(l.line_amount) AS everywhere\n'
    sql << '  FROM dash_demo.order_lines l\n'
    sql << '  JOIN dash_demo.orders o ON o.order_id = l.order_id\n'
    sql << '  JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '  JOIN dash_demo.products pr ON pr.product_id = l.product_id\n'
    sql << '  WHERE o.status <> \'cancelled\'\n'
    sql << '  GROUP BY pr.category\n'
    sql << ')\n'
    sql << 'SELECT c.category AS category,\n'
    sql << '       round(100.0 * c.here / sum(c.here) OVER (), 2) AS share_here_pct,\n'
    sql << '       round(100.0 * c.everywhere / sum(c.everywhere) OVER (), 2) AS share_everywhere_pct\n'
    sql << 'FROM per_category c\n'
    sql << 'ORDER BY share_here_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd25-chart-category-share-here-vs-everyone', data)
}

// ─── Widget: chart_dd25-chart-quarterly-index (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd25-chart-quarterly-index') {
    def sql = new StringBuilder()
    def params = []
    sql << 'WITH per_quarter AS (\n'
    sql << '  SELECT date_trunc(\'quarter\', o.order_ts)::DATE AS quarter,\n'
    if (hasCountry) {
        sql << '         sum(CASE WHEN g.country = ? THEN o.total_amount ELSE 0 END) AS here,\n'
        params << asDeclaredType('country', 'String', country)
    }
    sql << '         sum(o.total_amount) AS everywhere\n'
    sql << '  FROM dash_demo.orders o\n'
    sql << '  JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << '  WHERE o.status <> \'cancelled\'\n'
    sql << '  GROUP BY quarter\n'
    sql << ')\n'
    sql << 'SELECT q.quarter AS quarter,\n'
    sql << '       round(100.0 * q.here / first_value(q.here) OVER (ORDER BY q.quarter), 2) AS index_here,\n'
    sql << '       round(100.0 * q.everywhere / first_value(q.everywhere) OVER (ORDER BY q.quarter), 2) AS index_everywhere\n'
    sql << 'FROM per_quarter q\n'
    sql << 'ORDER BY q.quarter\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd25-chart-quarterly-index', data)
}

// ─── Widget: chart_dd25-chart-channel-mix-here (type=chart, dataSource=sql) ───
if (!componentId || componentId == 'chart_dd25-chart-channel-mix-here') {
    def sql = new StringBuilder()
    def params = []
    sql << 'SELECT o.channel AS channel,\n'
    sql << '       round(100.0 * count(*) / sum(count(*)) OVER (), 2) AS share_pct\n'
    sql << 'FROM dash_demo.orders o\n'
    sql << 'JOIN dash_demo.geo_cities g ON g.city_id = o.city_id\n'
    sql << 'WHERE true\n'
    if (hasCountry) {
        sql << '  AND g.country = ?\n'
        params << asDeclaredType('country', 'String', country)
    } else {
        sql << '  AND 1=1\n'   // no value: this filter is off
    }
    sql << 'GROUP BY o.channel\n'
    sql << 'ORDER BY share_pct DESC\n'
    def data = params.isEmpty() ? dbSql.rows(sql.toString()) : dbSql.rows(sql.toString(), params)
    ctx.reportData('chart_dd25-chart-channel-mix-here', data)
}

